---
title: "Weekly"
author: "Azura Liu"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstatix)
library("dplyr")
library("tidyverse")
library("lubridate")
library("readxl")
library(writexl)
library(datarium)
library(lme4)
library(lmerTest)
library(emmeans)
library(drc)
library(nlme)
library(nlstools)
library(multcomp)
library(ggpubr)
library(data.table)
```

```{r}
Sapflow<-read_excel("../Data/Processed/Daytime/sapflow/Join_4Blocks.xlsx")
Sapflow$Week <- cut(Sapflow$DOY,
              breaks=c(0, 156,161,166,171,176,181,186,191,196,201,206,211,216,221,226,231,236,241,246,251,256,261,266,271,276),
              labels=c('1', '2', '3', '4',"5","6","7","8","9","10","11","12","13","14","15","16", "17","18","19","20", "21","22", "23","24","25" ))
Sapflow<-Sapflow[c(2,5,6,7,10,13,14)]

```

```{r}
Weekly<-aggregate(Sapflow, by=list(Sapflow$Week,Sapflow$Block,Sapflow$Geno,Sapflow$Density), FUN = mean)

names(Weekly)[1]<-"Week"

names(Weekly)[4]<-"Density"
names(Weekly)[3]<-"Genotype"

Weekly<-Weekly[c(1,3:6,9,10)]
Weekly<-Weekly%>%
  mutate(ID=paste0(Density,Genotype))
```

```{r}
HA<-Weekly%>%filter(ID == "HA")
LA<-Weekly%>%filter(ID == "LA")
HB<-Weekly%>%filter(ID == "HB")
LB<-Weekly%>%filter(ID == "LB")
HC<-Weekly%>%filter(ID == "HC")
LC<-Weekly%>%filter(ID == "LC")
HO<-Weekly%>%filter(ID == "HO")
LO<-Weekly%>%filter(ID == "LO")
```

```{r}
fm1 <- lmer(SapflowPerGroundArea ~ log(VPD) + (log(VPD) | Block), HA)
dd <- ranef(fm1)[["Block"]]
dd <- cbind(Block=rownames(dd),dd)
dd
write.table(dd , file = "../Data/Processed/Daytime/sapflow/Slope.csv")

```



```{r}
coef(lm(SapflowPerGroundArea ~ log(VPD), HA[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HA[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HA[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HA[Weekly$Block == "4", ]))


coef(lm(SapflowPerGroundArea ~ log(VPD), LA[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LA[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LA[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LA[Weekly$Block == "4", ]))

coef(lm(SapflowPerGroundArea ~ log(VPD), HB[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HB[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HB[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HB[Weekly$Block == "4", ]))

coef(lm(SapflowPerGroundArea ~ log(VPD), LB[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LB[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LB[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LB[Weekly$Block == "4", ]))

coef(lm(SapflowPerGroundArea ~ log(VPD), HC[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HC[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HC[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HC[Weekly$Block == "4", ]))

coef(lm(SapflowPerGroundArea ~ log(VPD), LC[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LC[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LC[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LC[Weekly$Block == "4", ]))

coef(lm(SapflowPerGroundArea ~ log(VPD), HO[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HO[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HO[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), HO[Weekly$Block == "4", ]))

coef(lm(SapflowPerGroundArea ~ log(VPD), LO[Weekly$Block == "1", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LO[Weekly$Block == "2", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LO[Weekly$Block == "3", ]))
coef(lm(SapflowPerGroundArea ~ log(VPD), LO[Weekly$Block == "4", ]))


```

```{r}
Slopes<-read_excel("../Data/Processed/Daytime/sapflow/Slopes.xlsx")
Slopes<-Slopes[c(-7,-9)]

REW<-Slopes%>%filter(Covariate=="REW")
VPD<-Slopes%>%filter(Covariate=="VPD")

m0<-aov(Slope~Density*Genotype+(1|Block), data = REW,type="II")
TukeyHSD(m0)
anova(m0)
m0
summary(m0)
emmeans(m0, ~Density:Genotype,data=REW)

m1<-aov(Intercept~Density*Genotype+(1|Block), data = VPD,type="II")

summary(m1)
TukeyHSD(m1)
```





