---
title: "NSPlot"
author: "Azura Liu"
date: '2022-03-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("tidyverse")
library("lubridate")

getwd()
raw1<-read.csv("../Data/Processed/KtoSap/Sap1.csv")
raw2<-read.csv("../Data/Processed/KtoSap/Sap2.csv")
raw3<-read.csv("../Data/Processed/KtoSap/Sap3.csv")
raw4<-read.csv("../Data/Processed/KtoSap/Sap4.csv")

names(raw1)[1]<-"Index"
```

```{r more setup}
raw1$Date<-as.Date(raw1$Date, format = "%m/%d/%Y")
raw2$Date<-as.Date(raw2$Date, format = "%m/%d/%Y")
raw3$Date<-as.Date(raw3$Date, format = "%m/%d/%Y")
raw4$Date<-as.Date(raw4$Date, format = "%m/%d/%Y")

raw1<-raw1%>%mutate_if(is.character, as.numeric)
raw2<-raw2%>%mutate_if(is.character, as.numeric)
raw3<-raw3%>%mutate_if(is.character, as.numeric)
raw4<-raw4%>%mutate_if(is.character, as.numeric)
```

```{r S1 HC}
S1.f10<-raw1[1:960,]
S1.s10<-raw1[961:1920,]
S1.t10<-raw1[1921:2880,]

HCO1.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HCOS1, color = "HCOS1",shape = "."))+
  geom_point(aes(y=HCON1, color = "HCON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO1.1
ggsave("../Data/Plots/NS/S1/HCO1.1.jpg", HCO1.1, height = 2, width = 45, units = "in", dpi = 500)

HCO1.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HCOS1, color = "HCOS1",shape = "."))+
  geom_point(aes(y=HCON1, color = "HCON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO1.2
ggsave("../Data/Plots/NS/S1/HCO1.2.jpg", HCO1.2, height = 2, width = 45, units = "in", dpi = 500)

HCO1.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HCOS1, color = "HCOS1",shape = "."))+
  geom_point(aes(y=HCON1, color = "HCON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO1.3
ggsave("../Data/Plots/NS/S1/HCO1.3.jpg", HCO1.3, height = 2, width = 45, units = "in", dpi = 500)




HCO2.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HCOS2, color = "HCOS2",shape = "."))+
  geom_point(aes(y=HCON2, color = "HCON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO2.1
ggsave("../Data/Plots/NS/S1/HCO2.1.jpg", HCO2.1, height = 2, width = 45, units = "in", dpi = 500)

HCO2.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HCOS2, color = "HCOS2",shape = "."))+
  geom_point(aes(y=HCON2, color = "HCON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO2.2
ggsave("../Data/Plots/NS/S1/HCO2.2.jpg", HCO2.2, height = 2, width = 45, units = "in", dpi = 500)

HCO2.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HCOS2, color = "HCOS2",shape = "."))+
  geom_point(aes(y=HCON2, color = "HCON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO2.3
ggsave("../Data/Plots/NS/S1/HCO2.3.jpg", HCO2.3, height = 2, width = 45, units = "in", dpi = 500)



HCO4.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HCOS4, color = "HCOS4",shape = "."))+
  geom_point(aes(y=HCON4, color = "HCON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO4.1
ggsave("../Data/Plots/NS/S1/HCO4.1.jpg", HCO4.1, height = 2, width = 45, units = "in", dpi = 500)

HCO4.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HCOS4, color = "HCOS4",shape = "."))+
  geom_point(aes(y=HCON4, color = "HCON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO4.2
ggsave("../Data/Plots/NS/S1/HCO4.2.jpg", HCO4.2, height = 2, width = 45, units = "in", dpi = 500)

HCO4.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HCOS4, color = "HCOS4",shape = "."))+
  geom_point(aes(y=HCON4, color = "HCON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO4.3
ggsave("../Data/Plots/NS/S1/HCO4.3.jpg", HCO4.3, height = 2, width = 45, units = "in", dpi = 500)


HCO6.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HCOS6, color = "HCOS6",shape = "."))+
  geom_point(aes(y=HCON6, color = "HCON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO6.1
ggsave("../Data/Plots/NS/S1/HCO6.1.jpg", HCO6.1, height = 2, width = 45, units = "in", dpi = 500)

HCO6.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HCOS6, color = "HCOS6",shape = "."))+
  geom_point(aes(y=HCON6, color = "HCON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO6.2
ggsave("../Data/Plots/NS/S1/HCO6.2.jpg", HCO6.2, height = 2, width = 45, units = "in", dpi = 500)

HCO6.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HCOS6, color = "HCOS6",shape = "."))+
  geom_point(aes(y=HCON6, color = "HCON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO6.3
ggsave("../Data/Plots/NS/S1/HCO6.3.jpg", HCO6.3, height = 2, width = 45, units = "in", dpi = 500)


HCO8.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HCOS8, color = "HCOS8",shape = "."))+
  geom_point(aes(y=HCON8, color = "HCON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO8.1
ggsave("../Data/Plots/NS/S1/HCO8.1.jpg", HCO8.1, height = 2, width = 45, units = "in", dpi = 500)

HCO8.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HCOS8, color = "HCOS8",shape = "."))+
  geom_point(aes(y=HCON8, color = "HCON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO8.2
ggsave("../Data/Plots/NS/S1/HCO8.2.jpg", HCO8.2, height = 2, width = 45, units = "in", dpi = 500)

HCO8.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HCOS8, color = "HCOS8",shape = "."))+
  geom_point(aes(y=HCON8, color = "HCON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HCO8.3
ggsave("../Data/Plots/NS/S1/HCO8.3.jpg", HCO8.3, height = 2, width = 45, units = "in", dpi = 500)
```

```{r S1 LO}
LOO10.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LOOS10, color = "LOOS10",shape = "."))+
  geom_point(aes(y=LOON10, color = "LOON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO10.1
ggsave("../Data/Plots/NS/S1/LOO10.1.jpg", LOO10.1, height = 2, width = 45, units = "in", dpi = 500)

LOO10.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LOOS10, color = "LOOS10",shape = "."))+
  geom_point(aes(y=LOON10, color = "LOON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO10.2
ggsave("../Data/Plots/NS/S1/LOO10.2.jpg", LOO10.2, height = 2, width = 45, units = "in", dpi = 500)

LOO10.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LOOS10, color = "LOOS10",shape = "."))+
  geom_point(aes(y=LOON10, color = "LOON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO10.3
ggsave("../Data/Plots/NS/S1/LOO10.3.jpg", LOO10.3, height = 2, width = 45, units = "in", dpi = 500)




LOO11.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LOOS11, color = "LOOS11",shape = "."))+
  geom_point(aes(y=LOON11, color = "LOON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO11.1
ggsave("../Data/Plots/NS/S1/LOO11.1.jpg", LOO11.1, height = 2, width = 45, units = "in", dpi = 500)

LOO11.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LOOS11, color = "LOOS11",shape = "."))+
  geom_point(aes(y=LOON11, color = "LOON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO11.2
ggsave("../Data/Plots/NS/S1/LOO11.2.jpg", LOO11.2, height = 2, width = 45, units = "in", dpi = 500)

LOO11.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LOOS11, color = "LOOS11",shape = "."))+
  geom_point(aes(y=LOON11, color = "LOON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO11.3
ggsave("../Data/Plots/NS/S1/LOO11.3.jpg", LOO11.3, height = 2, width = 45, units = "in", dpi = 500)




LOO12.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LOOS12, color = "LOOS12",shape = "."))+
  geom_point(aes(y=LOON12, color = "LOON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO12.1
ggsave("../Data/Plots/NS/S1/LOO12.1.jpg", LOO12.1, height = 2, width = 45, units = "in", dpi = 500)

LOO12.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LOOS12, color = "LOOS12",shape = "."))+
  geom_point(aes(y=LOON12, color = "LOON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO12.2
ggsave("../Data/Plots/NS/S1/LOO12.2.jpg", LOO12.2, height = 2, width = 45, units = "in", dpi = 500)

LOO12.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LOOS12, color = "LOOS12",shape = "."))+
  geom_point(aes(y=LOON12, color = "LOON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO12.3
ggsave("../Data/Plots/NS/S1/LOO12.3.jpg", LOO12.3, height = 2, width = 45, units = "in", dpi = 500)




LOO14.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LOOS14, color = "LOOS14",shape = "."))+
  geom_point(aes(y=LOON14, color = "LOON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO14.1
ggsave("../Data/Plots/NS/S1/LOO14.1.jpg", LOO14.1, height = 2, width = 45, units = "in", dpi = 500)

LOO14.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LOOS14, color = "LOOS14",shape = "."))+
  geom_point(aes(y=LOON14, color = "LOON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO14.2
ggsave("../Data/Plots/NS/S1/LOO14.2.jpg", LOO14.2, height = 2, width = 45, units = "in", dpi = 500)

LOO14.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LOOS14, color = "LOOS14",shape = "."))+
  geom_point(aes(y=LOON14, color = "LOON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO14.3
ggsave("../Data/Plots/NS/S1/LOO14.3.jpg", LOO14.3, height = 2, width = 45, units = "in", dpi = 500)





LOO15.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LOOS15, color = "LOOS15",shape = "."))+
  geom_point(aes(y=LOON15, color = "LOON15",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO15.1
ggsave("../Data/Plots/NS/S1/LOO15.1.jpg", LOO15.1, height = 2, width = 45, units = "in", dpi = 500)

LOO15.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LOOS15, color = "LOOS15",shape = "."))+
  geom_point(aes(y=LOON15, color = "LOON15",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO15.2
ggsave("../Data/Plots/NS/S1/LOO15.2.jpg", LOO15.2, height = 2, width = 45, units = "in", dpi = 500)

LOO15.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LOOS15, color = "LOOS15",shape = "."))+
  geom_point(aes(y=LOON15, color = "LOON15",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO15.3
ggsave("../Data/Plots/NS/S1/LOO15.3.jpg", LOO15.3, height = 2, width = 45, units = "in", dpi = 500)





LOO17.1<-ggplot(S1.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LOOS17, color = "LOOS17",shape = "."))+
  geom_point(aes(y=LOON17, color = "LOON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO17.1
ggsave("../Data/Plots/NS/S1/LOO17.1.jpg", LOO17.1, height = 2, width = 45, units = "in", dpi = 500)

LOO17.2<-ggplot(S1.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LOOS17, color = "LOOS17",shape = "."))+
  geom_point(aes(y=LOON17, color = "LOON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO17.2
ggsave("../Data/Plots/NS/S1/LOO17.2.jpg", LOO17.2, height = 2, width = 45, units = "in", dpi = 500)

LOO17.3<-ggplot(S1.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LOOS17, color = "LOOS17",shape = "."))+
  geom_point(aes(y=LOON17, color = "LOON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LOO17.3
ggsave("../Data/Plots/NS/S1/LOO17.3.jpg", LOO17.3, height = 2, width = 45, units = "in", dpi = 500)
```


```{r S2 LC}
S2.f10<-raw2[1:960,]
S2.s10<-raw2[961:1920,]
S2.t10<-raw2[1921:2880,]

LCO1.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LCOS1, color = "LCOS1",shape = "."))+
  geom_point(aes(y=LCON1, color = "LCON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO1.1
ggsave("../Data/Plots/NS/S2/LCO1.1.jpg", LCO1.1, height = 2, width = 45, units = "in", dpi = 500)

LCO1.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LCOS1, color = "LCOS1",shape = "."))+
  geom_point(aes(y=LCON1, color = "LCON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO1.2
ggsave("../Data/Plots/NS/S2/LCO1.2.jpg", LCO1.2, height = 2, width = 45, units = "in", dpi = 500)

LCO1.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LCOS1, color = "LCOS1",shape = "."))+
  geom_point(aes(y=LCON1, color = "LCON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO1.3
ggsave("../Data/Plots/NS/S2/LCO1.3.jpg", LCO1.3, height = 2, width = 45, units = "in", dpi = 500)





LCO2.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LCOS2, color = "LCOS2",shape = "."))+
  geom_point(aes(y=LCON2, color = "LCON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO2.1
ggsave("../Data/Plots/NS/S2/LCO2.1.jpg", LCO2.1, height = 2, width = 45, units = "in", dpi = 500)

LCO2.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LCOS2, color = "LCOS2",shape = "."))+
  geom_point(aes(y=LCON2, color = "LCON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO2.2
ggsave("../Data/Plots/NS/S2/LCO2.2.jpg", LCO2.2, height = 2, width = 45, units = "in", dpi = 500)

LCO2.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LCOS2, color = "LCOS2",shape = "."))+
  geom_point(aes(y=LCON2, color = "LCON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO2.3
ggsave("../Data/Plots/NS/S2/LCO2.3.jpg", LCO2.3, height = 2, width = 45, units = "in", dpi = 500)






LCO4.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LCOS4, color = "LCOS4",shape = "."))+
  geom_point(aes(y=LCON4, color = "LCON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO4.1
ggsave("../Data/Plots/NS/S2/LCO4.1.jpg", LCO4.1, height = 2, width = 45, units = "in", dpi = 500)

LCO4.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LCOS4, color = "LCOS4",shape = "."))+
  geom_point(aes(y=LCON4, color = "LCON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO4.2
ggsave("../Data/Plots/NS/S2/LCO4.2.jpg", LCO4.2, height = 2, width = 45, units = "in", dpi = 500)

LCO4.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LCOS4, color = "LCOS4",shape = "."))+
  geom_point(aes(y=LCON4, color = "LCON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO4.3
ggsave("../Data/Plots/NS/S2/LCO4.3.jpg", LCO4.3, height = 2, width = 45, units = "in", dpi = 500)






LCO6.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LCOS6, color = "LCOS6",shape = "."))+
  geom_point(aes(y=LCON6, color = "LCON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO6.1
ggsave("../Data/Plots/NS/S2/LCO6.1.jpg", LCO6.1, height = 2, width = 45, units = "in", dpi = 500)

LCO6.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LCOS6, color = "LCOS6",shape = "."))+
  geom_point(aes(y=LCON6, color = "LCON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO6.2
ggsave("../Data/Plots/NS/S2/LCO6.2.jpg", LCO6.2, height = 2, width = 45, units = "in", dpi = 500)

LCO6.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LCOS6, color = "LCOS6",shape = "."))+
  geom_point(aes(y=LCON6, color = "LCON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO6.3
ggsave("../Data/Plots/NS/S2/LCO6.3.jpg", LCO6.3, height = 2, width = 45, units = "in", dpi = 500)




LCO8.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LCOS8, color = "LCOS8",shape = "."))+
  geom_point(aes(y=LCON8, color = "LCON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO8.1
ggsave("../Data/Plots/NS/S2/LCO8.1.jpg", LCO8.1, height = 2, width = 45, units = "in", dpi = 500)

LCO8.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LCOS8, color = "LCOS8",shape = "."))+
  geom_point(aes(y=LCON8, color = "LCON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO8.2
ggsave("../Data/Plots/NS/S2/LCO8.2.jpg", LCO8.2, height = 2, width = 45, units = "in", dpi = 500)

LCO8.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LCOS8, color = "LCOS8",shape = "."))+
  geom_point(aes(y=LCON8, color = "LCON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LCO8.3
ggsave("../Data/Plots/NS/S2/LCO8.3.jpg", LCO8.3, height = 2, width = 45, units = "in", dpi = 500)


```

```{r S2 HO}

HOO10.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HOOS10, color = "HOOS10",shape = "."))+
  geom_point(aes(y=HOON10, color = "HOON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO10.1
ggsave("../Data/Plots/NS/S2/HOO10.1.jpg", HOO10.1, height = 2, width = 45, units = "in", dpi = 500)

HOO10.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HOOS10, color = "HOOS10",shape = "."))+
  geom_point(aes(y=HOON10, color = "HOON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO10.2
ggsave("../Data/Plots/NS/S2/HOO10.2.jpg", HOO10.2, height = 2, width = 45, units = "in", dpi = 500)

HOO10.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HOOS10, color = "HOOS10",shape = "."))+
  geom_point(aes(y=HOON10, color = "HOON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO10.3
ggsave("../Data/Plots/NS/S2/HOO10.3.jpg", HOO10.3, height = 2, width = 45, units = "in", dpi = 500)




HOO11.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HOOS11, color = "HOOS11",shape = "."))+
  geom_point(aes(y=HOON11, color = "HOON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO11.1
ggsave("../Data/Plots/NS/S2/HOO11.1.jpg", HOO11.1, height = 2, width = 45, units = "in", dpi = 500)

HOO11.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HOOS11, color = "HOOS11",shape = "."))+
  geom_point(aes(y=HOON11, color = "HOON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO11.2
ggsave("../Data/Plots/NS/S2/HOO11.2.jpg", HOO11.2, height = 2, width = 45, units = "in", dpi = 500)

HOO11.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HOOS11, color = "HOOS11",shape = "."))+
  geom_point(aes(y=HOON11, color = "HOON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO11.3
ggsave("../Data/Plots/NS/S2/HOO11.3.jpg", HOO11.3, height = 2, width = 45, units = "in", dpi = 500)




HOO12.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HOOS12, color = "HOOS12",shape = "."))+
  geom_point(aes(y=HOON12, color = "HOON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO12.1
ggsave("../Data/Plots/NS/S2/HOO12.1.jpg", HOO12.1, height = 2, width = 45, units = "in", dpi = 500)

HOO12.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HOOS12, color = "HOOS12",shape = "."))+
  geom_point(aes(y=HOON12, color = "HOON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO12.2
ggsave("../Data/Plots/NS/S2/HOO12.2.jpg", HOO12.2, height = 2, width = 45, units = "in", dpi = 500)

HOO12.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HOOS12, color = "HOOS12",shape = "."))+
  geom_point(aes(y=HOON12, color = "HOON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO12.3
ggsave("../Data/Plots/NS/S2/HOO12.3.jpg", HOO12.3, height = 2, width = 45, units = "in", dpi = 500)





HOO14.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HOOS14, color = "HOOS14",shape = "."))+
  geom_point(aes(y=HOON14, color = "HOON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO14.1
ggsave("../Data/Plots/NS/S2/HOO14.1.jpg", HOO14.1, height = 2, width = 45, units = "in", dpi = 500)

HOO14.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HOOS14, color = "HOOS14",shape = "."))+
  geom_point(aes(y=HOON14, color = "HOON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO14.2
ggsave("../Data/Plots/NS/S2/HOO14.2.jpg", HOO14.2, height = 2, width = 45, units = "in", dpi = 500)

HOO14.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HOOS14, color = "HOOS14",shape = "."))+
  geom_point(aes(y=HOON14, color = "HOON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO14.3
ggsave("../Data/Plots/NS/S2/HOO14.3.jpg", HOO14.3, height = 2, width = 45, units = "in", dpi = 500)





HOO16.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HOOS16, color = "HOOS16",shape = "."))+
  geom_point(aes(y=HOON16, color = "HOON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO16.1
ggsave("../Data/Plots/NS/S2/HOO16.1.jpg", HOO16.1, height = 2, width = 45, units = "in", dpi = 500)

HOO16.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HOOS16, color = "HOOS16",shape = "."))+
  geom_point(aes(y=HOON16, color = "HOON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO16.2
ggsave("../Data/Plots/NS/S2/HOO16.2.jpg", HOO16.2, height = 2, width = 45, units = "in", dpi = 500)

HOO16.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HOOS16, color = "HOOS16",shape = "."))+
  geom_point(aes(y=HOON16, color = "HOON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO16.3
ggsave("../Data/Plots/NS/S2/HOO16.3.jpg", HOO16.3, height = 2, width = 45, units = "in", dpi = 500)



HOO17.1<-ggplot(S2.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HOOS17, color = "HOOS17",shape = "."))+
  geom_point(aes(y=HOON17, color = "HOON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO17.1
ggsave("../Data/Plots/NS/S2/HOO17.1.jpg", HOO17.1, height = 2, width = 45, units = "in", dpi = 500)

HOO17.2<-ggplot(S2.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HOOS17, color = "HOOS17",shape = "."))+
  geom_point(aes(y=HOON17, color = "HOON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO17.2
ggsave("../Data/Plots/NS/S2/HOO17.2.jpg", HOO17.2, height = 2, width = 45, units = "in", dpi = 500)

HOO17.3<-ggplot(S2.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HOOS17, color = "HOOS17",shape = "."))+
  geom_point(aes(y=HOON17, color = "HOON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HOO17.3
ggsave("../Data/Plots/NS/S2/HOO17.3.jpg", HOO17.3, height = 2, width = 45, units = "in", dpi = 500)


```

```{r S3 LA}
S3.f10<-raw3[1:960,]
S3.s10<-raw3[961:1920,]
S3.t10<-raw3[1921:2880,]


LAO1.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LAOS1, color = "LAOS1",shape = "."))+
  geom_point(aes(y=LAON1, color = "LAON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO1.1
ggsave("../Data/Plots/NS/S3/LAO1.1.jpg", LAO1.1, height = 2, width = 45, units = "in", dpi = 500)

LAO1.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LAOS1, color = "LAOS1",shape = "."))+
  geom_point(aes(y=LAON1, color = "LAON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO1.2
ggsave("../Data/Plots/NS/S3/LAO1.2.jpg", LAO1.2, height = 2, width = 45, units = "in", dpi = 500)

LAO1.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LAOS1, color = "LAOS1",shape = "."))+
  geom_point(aes(y=LAON1, color = "LAON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO1.3
ggsave("../Data/Plots/NS/S3/LAO1.3.jpg", LAO1.3, height = 2, width = 45, units = "in", dpi = 500)





LAO2.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LAOS2, color = "LAOS2",shape = "."))+
  geom_point(aes(y=LAON2, color = "LAON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO2.1
ggsave("../Data/Plots/NS/S3/LAO2.1.jpg", LAO2.1, height = 2, width = 45, units = "in", dpi = 500)

LAO2.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LAOS2, color = "LAOS2",shape = "."))+
  geom_point(aes(y=LAON2, color = "LAON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO2.2
ggsave("../Data/Plots/NS/S3/LAO2.2.jpg", LAO2.2, height = 2, width = 45, units = "in", dpi = 500)

LAO2.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LAOS2, color = "LAOS2",shape = "."))+
  geom_point(aes(y=LAON2, color = "LAON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO2.3
ggsave("../Data/Plots/NS/S3/LAO2.3.jpg", LAO2.3, height = 2, width = 45, units = "in", dpi = 500)






LAO4.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LAOS4, color = "LAOS4",shape = "."))+
  geom_point(aes(y=LAON4, color = "LAON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO4.1
ggsave("../Data/Plots/NS/S3/LAO4.1.jpg", LAO4.1, height = 2, width = 45, units = "in", dpi = 500)

LAO4.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LAOS4, color = "LAOS4",shape = "."))+
  geom_point(aes(y=LAON4, color = "LAON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO4.2
ggsave("../Data/Plots/NS/S3/LAO4.2.jpg", LAO4.2, height = 2, width = 45, units = "in", dpi = 500)

LAO4.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LAOS4, color = "LAOS4",shape = "."))+
  geom_point(aes(y=LAON4, color = "LAON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO4.3
ggsave("../Data/Plots/NS/S3/LAO4.3.jpg", LAO4.3, height = 2, width = 45, units = "in", dpi = 500)






LAO6.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LAOS6, color = "LAOS6",shape = "."))+
  geom_point(aes(y=LAON6, color = "LAON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO6.1
ggsave("../Data/Plots/NS/S3/LAO6.1.jpg", LAO6.1, height = 2, width = 45, units = "in", dpi = 500)

LAO6.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LAOS6, color = "LAOS6",shape = "."))+
  geom_point(aes(y=LAON6, color = "LAON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO6.2
ggsave("../Data/Plots/NS/S3/LAO6.2.jpg", LAO6.2, height = 2, width = 45, units = "in", dpi = 500)

LAO6.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LAOS6, color = "LAOS6",shape = "."))+
  geom_point(aes(y=LAON6, color = "LAON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO6.3
ggsave("../Data/Plots/NS/S3/LAO6.3.jpg", LAO6.3, height = 2, width = 45, units = "in", dpi = 500)




LAO8.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LAOS8, color = "LAOS8",shape = "."))+
  geom_point(aes(y=LAON8, color = "LAON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO8.1
ggsave("../Data/Plots/NS/S3/LAO8.1.jpg", LAO8.1, height = 2, width = 45, units = "in", dpi = 500)

LAO8.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LAOS8, color = "LAOS8",shape = "."))+
  geom_point(aes(y=LAON8, color = "LAON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO8.2
ggsave("../Data/Plots/NS/S3/LAO8.2.jpg", LAO8.2, height = 2, width = 45, units = "in", dpi = 500)

LAO8.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LAOS8, color = "LAOS8",shape = "."))+
  geom_point(aes(y=LAON8, color = "LAON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LAO8.3
ggsave("../Data/Plots/NS/S3/LAO8.3.jpg", LAO8.3, height = 2, width = 45, units = "in", dpi = 500)

```

```{r S3 LB}

LBO10.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LBOS10, color = "LBOS10",shape = "."))+
  geom_point(aes(y=LBON10, color = "LBON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO10.1
ggsave("../Data/Plots/NS/S3/LBO10.1.jpg", LBO10.1, height = 2, width = 45, units = "in", dpi = 500)

LBO10.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LBOS10, color = "LBOS10",shape = "."))+
  geom_point(aes(y=LBON10, color = "LBON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO10.2
ggsave("../Data/Plots/NS/S3/LBO10.2.jpg", LBO10.2, height = 2, width = 45, units = "in", dpi = 500)

LBO10.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LBOS10, color = "LBOS10",shape = "."))+
  geom_point(aes(y=LBON10, color = "LBON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO10.3
ggsave("../Data/Plots/NS/S3/LBO10.3.jpg", LBO10.3, height = 2, width = 45, units = "in", dpi = 500)




LBO11.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LBOS11, color = "LBOS11",shape = "."))+
  geom_point(aes(y=LBON11, color = "LBON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO11.1
ggsave("../Data/Plots/NS/S3/LBO11.1.jpg", LBO11.1, height = 2, width = 45, units = "in", dpi = 500)

LBO11.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LBOS11, color = "LBOS11",shape = "."))+
  geom_point(aes(y=LBON11, color = "LBON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO11.2
ggsave("../Data/Plots/NS/S3/LBO11.2.jpg", LBO11.2, height = 2, width = 45, units = "in", dpi = 500)

LBO11.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LBOS11, color = "LBOS11",shape = "."))+
  geom_point(aes(y=LBON11, color = "LBON11",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO11.3
ggsave("../Data/Plots/NS/S3/LBO11.3.jpg", LBO11.3, height = 2, width = 45, units = "in", dpi = 500)




LBO12.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LBOS12, color = "LBOS12",shape = "."))+
  geom_point(aes(y=LBON12, color = "LBON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO12.1
ggsave("../Data/Plots/NS/S3/LBO12.1.jpg", LBO12.1, height = 2, width = 45, units = "in", dpi = 500)

LBO12.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LBOS12, color = "LBOS12",shape = "."))+
  geom_point(aes(y=LBON12, color = "LBON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO12.2
ggsave("../Data/Plots/NS/S3/LBO12.2.jpg", LBO12.2, height = 2, width = 45, units = "in", dpi = 500)

LBO12.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LBOS12, color = "LBOS12",shape = "."))+
  geom_point(aes(y=LBON12, color = "LBON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO12.3
ggsave("../Data/Plots/NS/S3/LBO12.3.jpg", LBO12.3, height = 2, width = 45, units = "in", dpi = 500)





LBO14.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LBOS14, color = "LBOS14",shape = "."))+
  geom_point(aes(y=LBON14, color = "LBON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO14.1
ggsave("../Data/Plots/NS/S3/LBO14.1.jpg", LBO14.1, height = 2, width = 45, units = "in", dpi = 500)

LBO14.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LBOS14, color = "LBOS14",shape = "."))+
  geom_point(aes(y=LBON14, color = "LBON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO14.2
ggsave("../Data/Plots/NS/S3/LBO14.2.jpg", LBO14.2, height = 2, width = 45, units = "in", dpi = 500)

LBO14.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LBOS14, color = "LBOS14",shape = "."))+
  geom_point(aes(y=LBON14, color = "LBON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO14.3
ggsave("../Data/Plots/NS/S3/LBO14.3.jpg", LBO14.3, height = 2, width = 45, units = "in", dpi = 500)





LBO16.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LBOS16, color = "LBOS16",shape = "."))+
  geom_point(aes(y=LBON16, color = "LBON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO16.1
ggsave("../Data/Plots/NS/S3/LBO16.1.jpg", LBO16.1, height = 2, width = 45, units = "in", dpi = 500)

LBO16.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LBOS16, color = "LBOS16",shape = "."))+
  geom_point(aes(y=LBON16, color = "LBON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO16.2
ggsave("../Data/Plots/NS/S3/LBO16.2.jpg", LBO16.2, height = 2, width = 45, units = "in", dpi = 500)

LBO16.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LBOS16, color = "LBOS16",shape = "."))+
  geom_point(aes(y=LBON16, color = "LBON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO16.3
ggsave("../Data/Plots/NS/S3/LBO16.3.jpg", LBO16.3, height = 2, width = 45, units = "in", dpi = 500)



LBO17.1<-ggplot(S3.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=LBOS17, color = "LBOS17",shape = "."))+
  geom_point(aes(y=LBON17, color = "LBON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO17.1
ggsave("../Data/Plots/NS/S3/LBO17.1.jpg", LBO17.1, height = 2, width = 45, units = "in", dpi = 500)

LBO17.2<-ggplot(S3.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=LBOS17, color = "LBOS17",shape = "."))+
  geom_point(aes(y=LBON17, color = "LBON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO17.2
ggsave("../Data/Plots/NS/S3/LBO17.2.jpg", LBO17.2, height = 2, width = 45, units = "in", dpi = 500)

LBO17.3<-ggplot(S3.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=LBOS17, color = "LBOS17",shape = "."))+
  geom_point(aes(y=LBON17, color = "LBON17",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
LBO17.3
ggsave("../Data/Plots/NS/S3/LBO17.3.jpg", LBO17.3, height = 2, width = 45, units = "in", dpi = 500)


```

```{r S4 HB}
S4.f10<-raw4[1:960,]
S4.s10<-raw4[961:1920,]
S4.t10<-raw4[1921:2880,]


HBO9.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HBOS9, color = "HBOS9",shape = "."))+
  geom_point(aes(y=HBON9, color = "HBON9",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO9.1
ggsave("../Data/Plots/NS/S4/HBO9.1.jpg", HBO9.1, height = 2, width = 45, units = "in", dpi = 500)

HBO9.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HBOS9, color = "HBOS9",shape = "."))+
  geom_point(aes(y=HBON9, color = "HBON9",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO9.2
ggsave("../Data/Plots/NS/S4/HBO9.2.jpg", HBO9.2, height = 2, width = 45, units = "in", dpi = 500)

HBO9.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HBOS9, color = "HBOS9",shape = "."))+
  geom_point(aes(y=HBON9, color = "HBON9",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO9.3
ggsave("../Data/Plots/NS/S4/HBO9.3.jpg", HBO9.3, height = 2, width = 45, units = "in", dpi = 500)



HBO10.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HBOS10, color = "HBOS10",shape = "."))+
  geom_point(aes(y=HBON10, color = "HBON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO10.1
ggsave("../Data/Plots/NS/S4/HBO10.1.jpg", HBO10.1, height = 2, width = 45, units = "in", dpi = 500)

HBO10.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HBOS10, color = "HBOS10",shape = "."))+
  geom_point(aes(y=HBON10, color = "HBON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO10.2
ggsave("../Data/Plots/NS/S4/HBO10.2.jpg", HBO10.2, height = 2, width = 45, units = "in", dpi = 500)

HBO10.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HBOS10, color = "HBOS10",shape = "."))+
  geom_point(aes(y=HBON10, color = "HBON10",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO10.3
ggsave("../Data/Plots/NS/S4/HBO10.3.jpg", HBO10.3, height = 2, width = 45, units = "in", dpi = 500)




HBO12.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HBOS12, color = "HBOS12",shape = "."))+
  geom_point(aes(y=HBON12, color = "HBON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO12.1
ggsave("../Data/Plots/NS/S4/HBO12.1.jpg", HBO12.1, height = 2, width = 45, units = "in", dpi = 500)

HBO12.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HBOS12, color = "HBOS12",shape = "."))+
  geom_point(aes(y=HBON12, color = "HBON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO12.2
ggsave("../Data/Plots/NS/S4/HBO12.2.jpg", HBO12.2, height = 2, width = 45, units = "in", dpi = 500)

HBO12.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HBOS12, color = "HBOS12",shape = "."))+
  geom_point(aes(y=HBON12, color = "HBON12",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO12.3
ggsave("../Data/Plots/NS/S4/HBO12.3.jpg", HBO12.3, height = 2, width = 45, units = "in", dpi = 500)





HBO14.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HBOS14, color = "HBOS14",shape = "."))+
  geom_point(aes(y=HBON14, color = "HBON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO14.1
ggsave("../Data/Plots/NS/S4/HBO14.1.jpg", HBO14.1, height = 2, width = 45, units = "in", dpi = 500)

HBO14.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HBOS14, color = "HBOS14",shape = "."))+
  geom_point(aes(y=HBON14, color = "HBON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO14.2
ggsave("../Data/Plots/NS/S4/HBO14.2.jpg", HBO14.2, height = 2, width = 45, units = "in", dpi = 500)

HBO14.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HBOS14, color = "HBOS14",shape = "."))+
  geom_point(aes(y=HBON14, color = "HBON14",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO14.3
ggsave("../Data/Plots/NS/S4/HBO14.3.jpg", HBO14.3, height = 2, width = 45, units = "in", dpi = 500)





HBO16.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HBOS16, color = "HBOS16",shape = "."))+
  geom_point(aes(y=HBON16, color = "HBON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO16.1
ggsave("../Data/Plots/NS/S4/HBO16.1.jpg", HBO16.1, height = 2, width = 45, units = "in", dpi = 500)

HBO16.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HBOS16, color = "HBOS16",shape = "."))+
  geom_point(aes(y=HBON16, color = "HBON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO16.2
ggsave("../Data/Plots/NS/S4/HBO16.2.jpg", HBO16.2, height = 2, width = 45, units = "in", dpi = 500)

HBO16.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HBOS16, color = "HBOS16",shape = "."))+
  geom_point(aes(y=HBON16, color = "HBON16",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HBO16.3
ggsave("../Data/Plots/NS/S4/HBO16.3.jpg", HBO16.3, height = 2, width = 45, units = "in", dpi = 500)

```

```{r S4 HA}

HAO1.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HAOS1, color = "HAOS1",shape = "."))+
  geom_point(aes(y=HAON1, color = "HAON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO1.1
ggsave("../Data/Plots/NS/S4/HAO1.1.jpg", HAO1.1, height = 2, width = 45, units = "in", dpi = 500)

HAO1.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HAOS1, color = "HAOS1",shape = "."))+
  geom_point(aes(y=HAON1, color = "HAON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO1.2
ggsave("../Data/Plots/NS/S4/HAO1.2.jpg", HAO1.2, height = 2, width = 45, units = "in", dpi = 500)

HAO1.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HAOS1, color = "HAOS1",shape = "."))+
  geom_point(aes(y=HAON1, color = "HAON1",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO1.3
ggsave("../Data/Plots/NS/S4/HAO1.3.jpg", HAO1.3, height = 2, width = 45, units = "in", dpi = 500)




HAO2.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HAOS2, color = "HAOS2",shape = "."))+
  geom_point(aes(y=HAON2, color = "HAON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO2.1
ggsave("../Data/Plots/NS/S4/HAO2.1.jpg", HAO2.1, height = 2, width = 45, units = "in", dpi = 500)

HAO2.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HAOS2, color = "HAOS2",shape = "."))+
  geom_point(aes(y=HAON2, color = "HAON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO2.2
ggsave("../Data/Plots/NS/S4/HAO2.2.jpg", HAO2.2, height = 2, width = 45, units = "in", dpi = 500)

HAO2.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HAOS2, color = "HAOS2",shape = "."))+
  geom_point(aes(y=HAON2, color = "HAON2",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO2.3
ggsave("../Data/Plots/NS/S4/HAO2.3.jpg", HAO2.3, height = 2, width = 45, units = "in", dpi = 500)



HAO3.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HAOS3, color = "HAOS3",shape = "."))+
  geom_point(aes(y=HAON3, color = "HAON3",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO3.1
ggsave("../Data/Plots/NS/S4/HAO3.1.jpg", HAO3.1, height = 2, width = 45, units = "in", dpi = 500)

HAO3.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HAOS3, color = "HAOS3",shape = "."))+
  geom_point(aes(y=HAON3, color = "HAON3",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO3.2
ggsave("../Data/Plots/NS/S4/HAO3.2.jpg", HAO3.2, height = 2, width = 45, units = "in", dpi = 500)

HAO3.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HAOS3, color = "HAOS3",shape = "."))+
  geom_point(aes(y=HAON3, color = "HAON3",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO3.3
ggsave("../Data/Plots/NS/S4/HAO3.3.jpg", HAO3.3, height = 2, width = 45, units = "in", dpi = 500)


HAO4.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HAOS4, color = "HAOS4",shape = "."))+
  geom_point(aes(y=HAON4, color = "HAON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO4.1
ggsave("../Data/Plots/NS/S4/HAO4.1.jpg", HAO4.1, height = 2, width = 45, units = "in", dpi = 500)

HAO4.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HAOS4, color = "HAOS4",shape = "."))+
  geom_point(aes(y=HAON4, color = "HAON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO4.2
ggsave("../Data/Plots/NS/S4/HAO4.2.jpg", HAO4.2, height = 2, width = 45, units = "in", dpi = 500)

HAO4.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HAOS4, color = "HAOS4",shape = "."))+
  geom_point(aes(y=HAON4, color = "HAON4",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO4.3
ggsave("../Data/Plots/NS/S4/HAO4.3.jpg", HAO4.3, height = 2, width = 45, units = "in", dpi = 500)


HAO6.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HAOS6, color = "HAOS6",shape = "."))+
  geom_point(aes(y=HAON6, color = "HAON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO6.1
ggsave("../Data/Plots/NS/S4/HAO6.1.jpg", HAO6.1, height = 2, width = 45, units = "in", dpi = 500)

HAO6.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HAOS6, color = "HAOS6",shape = "."))+
  geom_point(aes(y=HAON6, color = "HAON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO6.2
ggsave("../Data/Plots/NS/S4/HAO6.2.jpg", HAO6.2, height = 2, width = 45, units = "in", dpi = 500)

HAO6.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HAOS6, color = "HAOS6",shape = "."))+
  geom_point(aes(y=HAON6, color = "HAON6",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO6.3
ggsave("../Data/Plots/NS/S4/HAO6.3.jpg", HAO6.3, height = 2, width = 45, units = "in", dpi = 500)


HAO8.1<-ggplot(S4.f10, aes(Index))+
  scale_x_continuous(breaks = c(96,192,288,384,480,576,672,768,864))+
  geom_point(aes(y=HAOS8, color = "HAOS8",shape = "."))+
  geom_point(aes(y=HAON8, color = "HAON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO8.1
ggsave("../Data/Plots/NS/S4/HAO8.1.jpg", HAO8.1, height = 2, width = 45, units = "in", dpi = 500)

HAO8.2<-ggplot(S4.s10, aes(Index))+
  scale_x_continuous(breaks = c(1056,1152,1248,1344,1440,1536,1632,1728,1824))+
  geom_point(aes(y=HAOS8, color = "HAOS8",shape = "."))+
  geom_point(aes(y=HAON8, color = "HAON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO8.2
ggsave("../Data/Plots/NS/S4/HAO8.2.jpg", HAO8.2, height = 2, width = 45, units = "in", dpi = 500)

HAO8.3<-ggplot(S4.t10, aes(Index))+
  scale_x_continuous(breaks = c(2016,2112,2208,2304,2400,2496,2592,2688,2784))+
  geom_point(aes(y=HAOS8, color = "HAOS8",shape = "."))+
  geom_point(aes(y=HAON8, color = "HAON8",shape = "."))+
  #geom_point(aes(y=VPD*30, color = "VPD", shape = "."))+
  xlab("Entries")+ylab("Sapflux")
HAO8.3
ggsave("../Data/Plots/NS/S4/HAO8.3.jpg", HAO8.3, height = 2, width = 45, units = "in", dpi = 500)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
