---
title: "REW"
author: "Azura Liu"
date: "2022-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstatix)
library("dplyr")
library("tidyverse")
library("lubridate")
library("readxl")
library("writexl")
library(datarium)
library(lme4)
library(lmerTest)

getwd()
raw<-read_excel("../Data/Processed/ENV/SoMo17_Original.xlsx")
summary(raw)
```

```{r}

REW<-raw%>%
  mutate(HC = (HC-min(HC))/(max(HC)-min(HC)))%>%    
  mutate(LO = (LO-min(LO))/(max(LO)-min(LO)))%>%
  mutate(LC = (LC-min(LC))/(max(LC)-min(LC)))%>%
  mutate(HO = (HO-min(HO))/(max(HO)-min(HO)))%>%
  mutate(LA = (LA-min(LA))/(max(LA)-min(LA)))%>%
  mutate(LB = (LB-min(LB))/(max(LB)-min(LB)))%>%
  mutate(HA = (HA-min(HA))/(max(HA)-min(HA)))%>%
  mutate(HB = (HB-min(HB))/(max(HB)-min(HB)))


#write_xlsx(REW, "../Data/Processed/ENV/REW.xlsx")
```

```{r}
Sapflow<-read_excel("../Data/Processed/Daytime/sapflow/Join_4Blocks.xlsx")

#Sapflow<-Sapflow%>%
 # filter(Block == 1)
REW<-  aggregate(Sapflow[,c(5,13)],by = list(Sapflow$DOY,Sapflow$Density),FUN = "mean")
names(REW)[1]<-"DOY"
names(REW)[2]<-"Density"

Environ<-ggplot(REW,aes(x=DOY))+
  geom_line(aes(y=REW, color = Density),size = 4)+
  geom_line(aes(y=VPD, color = "VPD"),size = 4)+
  scale_y_continuous(
    name = "REW",
    sec.axis = sec_axis(~.,name = "VPD")
  )+ theme(axis.text = element_text(size = 20))+
  theme(axis.title.y = element_text(size = 20))+ 
  theme(axis.title.x = element_text(size = 20))+
  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20)) +
  guides(shape = guide_legend(override.aes = list(size = 40)))+guides(color = guide_legend(title = ""))

Environ
ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/REWnVPD2.jpg",  Environ, height = 10, width = 20, units = "in", dpi = 200)
summary(Sapflow)
Join<-inner_join(Sapflow, REW, by=c("DOY","ID"))%>%
  select(1:13)
Low<-Sapflow%>%filter(Density== "L")
High<-Sapflow%>%filter(Density == "H")

summary(High)
summary(Low)

names(Join)[13]<-"REW"
Join$SoMo<-as.factor(ifelse(Join$REW <0.4, 'Dry',
                     ifelse(Join$REW <0.6, 'Intermediate', 
                     ifelse(Join$REW <1, 'Wet'))))

#write_xlsx(Join, "../Data/Processed/ENV/Join_1Block.xlsx")

```


```{r eval=FALSE, include=FALSE}
Join1<-  aggregate(Join$REW, by = list(Join$DOY,Join$Density),FUN = "mean")
names(Join1)[1]<-"DOY"
names(Join1)[2]<-"Density"
names(Join1)[3]<-"REW"

High.REW<-Join1%>%filter(Density == "H")

Low.REW<-Join1%>%filter(Density == "L")

High.D.REW<-ggplot(Join1, aes(x=DOY, y = REW))+
  geom_point(aes(color = Density,size=1))+
   scale_x_continuous(breaks = pretty(Join1$DOY, n = 10))+
  ylim(0,1)+
  xlab("DOY")+ylab("REW (%)")+
 theme(text = element_text(size = 30))

High.D.REW
ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/REW/AverageREW.jpg",  High.D.REW, height = 10, width = 20, units = "in", dpi = 500)


```


```{r eval=FALSE, include=FALSE}
m<-lm(SapflowPerGroundArea ~ SoMo+ (1| DOY)+ (1| Block)  ,
          data = Join)
mm<-aov(m)
Tukey<-TukeyHSD(mm)
plot(Tukey, las = 1)




m
summary(m)
anova(m)
m1 <- lm(SapflowPerGroundArea ~ ID+VPD+ (1| DOY)+ (1| Block),
          data = Join)

coef(m1)
Join %>% 
    group_by(ID) %>% 
    do({
      mod = lm(SapflowPerGroundArea ~ VPD, data =Join)
      data.frame(Intercept = coef(mod)[1],
                 Slope = coef(mod)[2])
    })
m<-lm(SapflowPerGroundArea ~ VPD, data =Join)
Low<-Join%>%
  filter(SoMo == "Dry")

High<-Join%>%
  filter(SoMo == "Wet")

mLow<-aov(SapflowPerGroundArea ~ Density*Geno+  + (1| DOY) +(1|Block),
          data = Low)

mHigh<-aov(SapflowPerGroundArea ~ Density*Geno+  + (1| DOY) +(1|Block),
          data = High)

mHigh


summary(mHigh)
coef(mHigh)

AIC(m,m1)

anova(m1,m)
Tukey<-TukeyHSD(m)
plot(Tukey, las = 1)

boxplot(Join$SapflowPerGroundArea ~ Join$Density*Join$Geno*Join$SoMo,par(cex.axis=0.8))

tapply(High$SapflowPerGroundArea, High$ID, mean)
```

```{r}
NonZero<-Sapflow%>%filter(VPD>0)
names(NonZero)[7]<-"Genotype"





HA<-Raw%>%filter(Treatment == "HA")
LA<-Raw%>%filter(Treatment == "LA")
HB<-Raw%>%filter(Treatment == "HB")
LB<-Raw%>%filter(Treatment == "LB")
HC<-Raw%>%filter(Treatment == "HC")
LC<-Raw%>%filter(Treatment == "LC")
HO<-Raw%>%filter(Treatment == "HO")
LO<-Raw%>%filter(Treatment == "LO")
```

```{r}
VPD.group<-ggplot(NonZero, aes(x=VPD, y=SapflowPerGroundArea, shape=Density, linetype=Density,color=Genotype)) + 
  geom_point(size=4, alpha=0.3)+
  stat_smooth(method=lm, formula=y~log(x), size=5, se=FALSE)+
  xlab("VPD")+ylab("Sapflow (L/m^2)")+
 theme(text = element_text(size = 30),legend.key.size = unit(3, 'cm'))

VPD.group

REW.group<-ggplot(NonZero, aes(x=REW, y=SapflowPerGroundArea, shape=Density, linetype=Density, color=Genotype)) + 
  geom_point(size=4, alpha=0.3)+
  stat_smooth(method=lm, formula=y~log(x), size=5, se=FALSE)+
  xlab("REW")+ylab("Sapflow (L/m^2)")+
 theme(text = element_text(size = 30),legend.key.size = unit(3, 'cm'))

REW.group



ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/REWbyGroup.jpg", REW.group, height = 20, width = 20, units = "in", dpi = 100)

ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/VPDbyGroup.jpg", VPD.group, height = 20, width = 20, units = "in", dpi = 100)

Comparison<-ggarrange(VPD.group,REW.group, common.legend = TRUE,
          labels = c("VPD","REW"),
          ncol = 1, nrow = 2)
Comparison 
ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/Comparison.jpg", Comparison, height = 30, width = 20, units = "in", dpi = 100)

```

```{r}
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "HA"&NonZero$Block=="1", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "HA"&NonZero$Block=="2", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "HA"&NonZero$Block=="3", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "HA"&NonZero$Block=="4", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "LA", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "HB", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "LB", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "HC", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "LC", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "HO", ]))
summary(lm(SapflowPerGroundArea ~ log(REW), NonZero[NonZero$ID == "LO", ]))



```

```{r}




VPD.group<-ggplot(Join, aes(x=VPD, y=log(SapflowPerGroundArea), shape=ID, color=ID)) + 
  geom_point(size=4, alpha=0.5)+
  geom_smooth(method=lm, formula=log(y)~x, size=3,se=FALSE)+
  xlab("VPD (kPa)")+ylab("Sapflow per Ground Area (L/m^3)")+
 theme(text = element_text(size = 30),legend.key.size = unit(3, 'cm'))



ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/VPD/VPDbyGrouplogy.jpg",  VPD.group, height = 20, width = 20, units = "in", dpi = 100)

VPD.group<-ggplot(Join, aes(x=log(VPD), y=log(SapflowPerGroundArea), shape=ID, color=ID)) + 
  geom_point(size=4, alpha=0.5)+
  geom_smooth(method=lm, formula=log(y)~log(x), size=3,se=FALSE)+
  xlab("VPD (kPa)")+ylab("Sapflow per Ground Area (L/m^3)")+
 theme(text = element_text(size = 30),legend.key.size = unit(3, 'cm'))



ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/VPD/VPDbyGrouploglog.jpg",  VPD.group, height = 20, width = 20, units = "in", dpi = 100)


VPD.group<-ggplot(Join, aes(x=log(VPD), y=SapflowPerGroundArea, shape=ID, color=ID)) + 
  geom_point(size=4, alpha=0.5)+
  geom_smooth(method=lm, formula=y~log(x), size=3,se=FALSE)+
  xlab("VPD (kPa)")+ylab("Sapflow per Ground Area (L/m^3)")+
 theme(text = element_text(size = 30),legend.key.size = unit(3, 'cm'))



ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/VPD/VPDbyGrouplogx.jpg",  VPD.group, height = 20, width = 20, units = "in", dpi = 100)
```

