---
title: "SapfluxTests"
author: "Azura Liu"
date: "2022-10-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstatix)
library("dplyr")
library("tidyverse")
library("lubridate")
library("readxl")
library("writexl")
library(datarium)
library(lme4)
library(lmerTest)
#install.packages("emmeans")
library(emmeans)
library(ggpubr)

getwd()
Raw<-read_xlsx("../Data/Processed/Daytime/sapflow/Sapflux.xlsx")
Raw<-Raw%>%pivot_longer(cols=c(8:129), names_to="DOY", values_to="Sapflux")
Raw<-Raw%>%mutate(Treatment=paste0(Density,Genotype))
  

```

```{r}
SapfluxAnova<-aggregate(Raw$Sapflux,by = list(Raw$DOY,Raw$Genotype,Raw$Density,Raw$Tree), FUN = sum)
names(SapfluxAnova)[1]<-"DOY"
names(SapfluxAnova)[2]<-"Genotype"
names(SapfluxAnova)[3]<-"Density"
names(SapfluxAnova)[4]<-"Tree"
names(SapfluxAnova)[5]<-"Sapflux"


m0<-aov(Sapflux~Density*Genotype*DOY,data=SapfluxAnova)
m0
emmeans(m0, ~Density:Genotype,data=SapfluxAnova)
TukeyHSD(m0)

summary(m0)
```




```{r}
Sapflux<-Raw%>%pivot_wider(names_from="Orientation",values_from = "Sapflux")%>%
  na.omit()%>%
  mutate(Treatment=paste0(Density,Genotype))
Sapflux1<-Sapflux%>%pivot_longer(cols=c(7:8),names_to="Position",values_to="Sapflux")%>%
 # mutate(ID = paste0(Density, Genotype, Tree))%>%
  mutate(Treatment=paste0(Density,Genotype))
Sapflux2<-aggregate(Sapflux1$Sapflux, by=list(Sapflux1$DOY,Sapflux1$Treatment,Sapflux1$Position),mean)

names(Sapflux2)[1]<-"DOY"
names(Sapflux2)[2]<-"Treatment"
names(Sapflux2)[3]<-"Position"
names(Sapflux2)[4]<-"Sapflux"

Sapflux3<-Sapflux2%>%pivot_wider(values_from="Sapflux", names_from="Position")
summary<-group_by(Sapflux1, Orientation) %>%
  summarise(
    count = n(),
    mean = mean(Sapflux, na.rm = TRUE),
    sd = sd(Sapflux, na.rm = TRUE)
  )
print(summary)

t_test(Sapflux$I,Sapflux$O, paired=TRUE)
#write.table(summary , file = "../Data/Processed/Daytime/sapflow/sapfluxsummary.csv")
```

```{r}
#install.packages("stats")
library(stats)
t.test(Sapflux$N,Sapflux$S,data=Sapflux,paired=TRUE)
HA<-Sapflux1%>%filter(Treatment=="HA")
LA<-Sapflux1%>%filter(Treatment=="LA")
HB<-Sapflux1%>%filter(Treatment=="HB")
LB<-Sapflux1%>%filter(Treatment=="LB")
HC<-Sapflux1%>%filter(Treatment=="HC")
LC<-Sapflux1%>%filter(Treatment=="LC")
HO<-Sapflux1%>%filter(Treatment=="HO")
LO<-Sapflux1%>%filter(Treatment=="LO")


pairwise.t.test(HA$Sapflux, HA$Position, p.adjust.method = p.adjust.methods,paired=TRUE)
pairwise.t.test(LA$Sapflux, LA$Position, p.adjust.method = p.adjust.methods,paired=TRUE)
pairwise.t.test(HB$Sapflux, HB$Position, p.adjust.method = p.adjust.methods,paired=TRUE)
pairwise.t.test(LB$Sapflux, LB$Position, p.adjust.method = p.adjust.methods,paired=TRUE)
pairwise.t.test(HC$Sapflux, HC$Position, p.adjust.method = p.adjust.methods,paired=TRUE)
pairwise.t.test(LC$Sapflux, LC$Position, p.adjust.method = p.adjust.methods,paired=TRUE)
pairwise.t.test(HO$Sapflux, HO$Position, p.adjust.method = p.adjust.methods,paired=TRUE)
pairwise.t.test(LO$Sapflux, LO$Position, p.adjust.method = p.adjust.methods,paired=TRUE)

```


```{r}
 Sapflux1 %>%
  pairwise_t_test(
    Sapflux ~ Position, paired = TRUE,
    p.adjust.method = "bonferroni"
    )


```



```{r}
Raw<-aggregate(Raw$Sapflux, by=list(Raw$DOY,Raw$Treatment,Raw$Position),mean)
names(Raw)[1]<-"DOY"
names(Raw)[2]<-"Treatment"
names(Raw)[3]<-"Position"
names(Raw)[4]<-"Sapflux"
```
```{r}


#geom_line(size=1,alpha=0.8)+
HAIO<-ggplot(HA,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+ylab("Sapflux(g/cm^2/s)")+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000)+ theme(axis.text = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 20))+ 
 theme(axis.title.x = element_blank())+  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))


HAIO

LAIO<-ggplot(LA,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000)+ theme(axis.text = element_text(size = 15))+
  theme(axis.title.y = element_blank())+ 
 theme(axis.title.x = element_blank())+  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))


LAIO

HBIO<-ggplot(HB,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+ ylab("Sapflux(g/cm^2/s)")+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000)+ theme(axis.text = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 15))+ 
 theme(axis.title.x = element_blank())+  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))


HBIO

LBIO<-ggplot(LB,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000)+ theme(axis.text = element_text(size = 15))+
  theme(axis.title.y =  element_blank())+ 
 theme(axis.title.x = element_blank())+  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))


LBIO

HCIO<-ggplot(HC,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+ylab("Sapflux(g/cm^2/s)")+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000)+ theme(axis.text = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 20))+ 
 theme(axis.title.x = element_blank())+  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))


HCIO

LCIO<-ggplot(LC,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000)+ theme(axis.text = element_text(size = 15))+
  theme(axis.title.y =  element_blank())+ 
  theme(axis.title.x = element_blank())+
  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))

LCIO

HOIO<-ggplot(HO,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+ylab("Sapflux(g/cm^2/s)")+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000) + theme(axis.text = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 20))+ 
  theme(axis.title.x = element_text(size = 20))+
  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))


HOIO


LOIO<-ggplot(LO,aes(x=DOY,y=Sapflux,color=Position,group=Position))+geom_point(size=2)+geom_line(size=1,alpha=0.8)+
  scale_x_discrete(breaks = c("150","175","200","225","250","275"))+
  theme(plot.margin = margin(1,0.5,1,0.5, "cm")) +
  ylim(0,4000)+ theme(axis.text = element_text(size = 15))+
  theme(axis.title.y =  element_blank())+ 
  theme(axis.title.x = element_text(size = 20))+
  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20))





LOIO

```

```{r}
ggsave("../Data/Processed/Daytime/Sapflux/Plots/HAIO.jpg", HAIO, height = 7, width = 10, units = "in", dpi = 500)
ggsave("../Data/Processed/Daytime/Sapflux/Plots/LAIO.jpg", LAIO, height = 7, width = 10, units = "in", dpi = 500)
ggsave("../Data/Processed/Daytime/Sapflux/Plots/HBIO.jpg", HBIO, height = 7, width = 10, units = "in", dpi = 500)
ggsave("../Data/Processed/Daytime/Sapflux/Plots/LBIO.jpg", LBIO, height = 7, width = 10, units = "in", dpi = 500)
ggsave("../Data/Processed/Daytime/Sapflux/Plots/HCIO.jpg", HCIO, height = 7, width = 10, units = "in", dpi = 500)
ggsave("../Data/Processed/Daytime/Sapflux/Plots/LCIO.jpg", LCIO, height = 7, width = 10, units = "in", dpi = 500)
ggsave("../Data/Processed/Daytime/Sapflux/Plots/HOIO.jpg", HOIO, height = 7, width = 10, units = "in", dpi = 500)
ggsave("../Data/Processed/Daytime/Sapflux/Plots/LOIO.jpg", LOIO, height = 7, width = 10, units = "in", dpi = 500)


#par(mfrow=c(4,2))
  




```



```{r}
IvsO<-ggarrange(HAIO+ rremove("x.text"),LAIO+ rremove("x.text"),HBIO+ rremove("x.text"),LBIO+ rremove("x.text"),HCIO+ rremove("x.text"),LCIO+ rremove("x.text"),HOIO,LOIO, common.legend = TRUE,
          labels = c("HA", "LA", "HB","LB","HC","LC","HO","LO"),font.label = list(size = 20),hjust=-0.5,
          ncol = 2, nrow = 4)
IvsO
ggsave("../Data/Processed/Daytime/Sapflux/Plots/IOMean.jpg", IvsO, height = 14, width = 10, units = "in", dpi = 500)


```
