---
title: "Sapwood Area"
author: "Azura Liu"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("tidyverse")
library("lubridate")
library("readxl")
library("writexl")

getwd()
DailySection<-read_excel("../Data/Processed/Sapwood/17Sapwood.xlsx")
```

```{r eval=FALSE, include=FALSE}
LA1<-DailySection%>%
   select(1,contains("1211LA"))%>%  
  pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LA2<-DailySection%>%
   select(1,contains("2211LA"))%>%   
  pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LA3<-DailySection%>%
   select(1,contains("3211LA"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LA4<-DailySection%>%
   select(1,contains("4211LA"))%>%   pivot_longer(cols=c(2:23), names_to="ID", values_to="Sapwood")

LA<-rbind(LA1,LA2,LA3,LA4)

LB1<-DailySection%>%
   select(1,contains("1311LB"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LB2<-DailySection%>%
   select(1,contains("2311LB"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LB3<-DailySection%>%
   select(1,contains("3311LB"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LB4<-DailySection%>%
   select(1,contains("4311LB"))%>%   pivot_longer(cols=c(2:20), names_to="ID", values_to="Sapwood")

LC1<-DailySection%>%
     select(1,contains("1411LC"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LC2<-DailySection%>%
     select(1,contains("2411LC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LC3<-DailySection%>%
     select(1,contains("3411LC"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LC4<-DailySection%>%
     select(1,contains("4411LC"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LO1<-DailySection%>%
     select(1,contains("1611LO"))%>%   pivot_longer(cols=c(2:23), names_to="ID", values_to="Sapwood")
LO2<-DailySection%>%
     select(1,contains("2611LO"))%>%   pivot_longer(cols=c(2:23), names_to="ID", values_to="Sapwood")
LO3<-DailySection%>%
     select(1,contains("3611LO"))%>%   pivot_longer(cols=c(2:20), names_to="ID", values_to="Sapwood")
LO4<-DailySection%>%
     select(1,contains("4611LO"))%>%   pivot_longer(cols=c(2:20), names_to="ID", values_to="Sapwood")
HA1<-DailySection%>%
     select(1,contains("1231HA"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
HA2<-DailySection%>%
     select(1,contains("2231HA"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HA3<-DailySection%>%
     select(1,contains("3231HA"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HA4<-DailySection%>%
     select(1,contains("4231HA"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")

HB1<-DailySection%>%
     select(1,contains("1331HB"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
HB2<-DailySection%>%
     select(1,contains("2331HB"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
HB3<-DailySection%>%
     select(1,contains("3331HB"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
HB4<-DailySection%>%
     select(1,contains("4331HB"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")

HC1<-DailySection%>%
     select(1,contains("1431HC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HC2<-DailySection%>%
     select(1,contains("2431HC"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
HC3<-DailySection%>%
     select(1,contains("3431HC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HC4<-DailySection%>%
     select(1,contains("4431HC"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")

HO1<-DailySection%>%
     select(1,contains("1631HO"))%>%   pivot_longer(cols=c(2:22), names_to="ID", values_to="Sapwood")
HO2<-DailySection%>%
     select(1,contains("2631HO"))%>%   pivot_longer(cols=c(2:22), names_to="ID", values_to="Sapwood")
HO3<-DailySection%>%
     select(1,contains("3631HO"))%>%   pivot_longer(cols=c(2:21), names_to="ID", values_to="Sapwood")
HO4<-DailySection%>%
     select(1,contains("4631HO"))%>%   pivot_longer(cols=c(2:20), names_to="ID", values_to="Sapwood")


```

```{r eval=FALSE, include=FALSE}
LA1<-DailySection%>%
   select(1,contains("1211LA"))%>%  pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LA2<-DailySection%>%
   select(1,contains("2211LA"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
LA3<-DailySection%>%
   select(1,contains("3211LA"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
LA4<-DailySection%>%
   select(1,contains("4211LA"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")

LA<-rbind(LA1,LA2,LA3,LA4)
LASapwood<-aggregate(LA$Sapwood, by = list(LA$DOY),FUN = "sum")%>%
  mutate("ID"="LA")
names(LASapwood)[1]<-"DOY"
names(LASapwood)[2]<-"Area"

LB1<-DailySection%>%
   select(1,contains("1311LB"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LB2<-DailySection%>%
   select(1,contains("2311LB"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
LB3<-DailySection%>%
   select(1,contains("3311LB"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
LB4<-DailySection%>%
   select(1,contains("4311LB"))%>%   pivot_longer(cols=c(2:21), names_to="ID", values_to="Sapwood")
LB<-rbind(LB1,LB2,LB3,LB4)
LBSapwood<-aggregate(LB$Sapwood, by = list(LB$DOY),FUN = "sum")%>%
  mutate("ID"="LB")
names(LBSapwood)[1]<-"DOY"
names(LBSapwood)[2]<-"Area"



LC1<-DailySection%>%
     select(1,contains("1411LC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LC2<-DailySection%>%
     select(1,contains("2411LC"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
LC3<-DailySection%>%
     select(1,contains("3411LC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LC4<-DailySection%>%
     select(1,contains("4411LC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
LC<-rbind(LC1,LC2,LC3,LC4)
LCSapwood<-aggregate(LC$Sapwood, by = list(LC$DOY),FUN = "sum")%>%
  mutate("ID"="LC")
names(LCSapwood)[1]<-"DOY"
names(LCSapwood)[2]<-"Area"


LO1<-DailySection%>%
     select(1,contains("1611LO"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LO2<-DailySection%>%
     select(1,contains("2611LO"))%>%   pivot_longer(cols=c(2:24), names_to="ID", values_to="Sapwood")
LO3<-DailySection%>%
     select(1,contains("3611LO"))%>%   pivot_longer(cols=c(2:21), names_to="ID", values_to="Sapwood")
LO4<-DailySection%>%
     select(1,contains("4611LO"))%>%   pivot_longer(cols=c(2:21), names_to="ID", values_to="Sapwood")
LO<-rbind(LO1,LO2,LO3,LO4)
LOSapwood<-aggregate(LO$Sapwood, by = list(LO$DOY),FUN = "sum")%>%
  mutate("ID"="LO")
names(LOSapwood)[1]<-"DOY"
names(LOSapwood)[2]<-"Area"


HA1<-DailySection%>%
     select(1,contains("1231HA"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HA2<-DailySection%>%
     select(1,contains("2231HA"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
HA3<-DailySection%>%
     select(1,contains("3231HA"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
HA4<-DailySection%>%
     select(1,contains("4231HA"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
HA<-rbind(HA1,HA2,HA3,HA4)
HASapwood<-aggregate(HA$Sapwood, by = list(HA$DOY),FUN = "sum")%>%
  mutate("ID"="HA")
names(HASapwood)[1]<-"DOY"
names(HASapwood)[2]<-"Area"


HB1<-DailySection%>%
     select(1,contains("1331HB"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HB2<-DailySection%>%
     select(1,contains("2331HB"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HB3<-DailySection%>%
     select(1,contains("3331HB"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HB4<-DailySection%>%
     select(1,contains("4331HB"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HB<-rbind(HB1,HB2,HB3,HB4)
HBSapwood<-aggregate(HB$Sapwood, by = list(HB$DOY),FUN = "sum")%>%
  mutate("ID"="HB")
names(HBSapwood)[1]<-"DOY"
names(HBSapwood)[2]<-"Area"



HC1<-DailySection%>%
     select(1,contains("1431HC"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
HC2<-DailySection%>%
     select(1,contains("2431HC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HC3<-DailySection%>%
     select(1,contains("3431HC"))%>%   pivot_longer(cols=c(2:26), names_to="ID", values_to="Sapwood")
HC4<-DailySection%>%
     select(1,contains("4431HC"))%>%   pivot_longer(cols=c(2:25), names_to="ID", values_to="Sapwood")
HC<-rbind(HC1,HC2,HC3,HC4)
HCSapwood<-aggregate(HC$Sapwood, by = list(HC$DOY),FUN = "sum")%>%
  mutate("ID"="HC")
names(HCSapwood)[1]<-"DOY"
names(HCSapwood)[2]<-"Area"



HO1<-DailySection%>%
     select(1,contains("1631HO"))%>%   pivot_longer(cols=c(2:23), names_to="ID", values_to="Sapwood")
HO2<-DailySection%>%
     select(1,contains("2631HO"))%>%   pivot_longer(cols=c(2:23), names_to="ID", values_to="Sapwood")
HO3<-DailySection%>%
     select(1,contains("3631HO"))%>%   pivot_longer(cols=c(2:22), names_to="ID", values_to="Sapwood")
HO4<-DailySection%>%
     select(1,contains("4631HO"))%>%   pivot_longer(cols=c(2:21), names_to="ID", values_to="Sapwood")
HO<-rbind(HO1,HO2,HO3,HO4)
HOSapwood<-aggregate(HO$Sapwood, by = list(HO$DOY),FUN = "sum")%>%
  mutate("ID"="HO")
names(HOSapwood)[1]<-"DOY"
names(HOSapwood)[2]<-"Area"

PlotLevel<-rbind(LASapwood,LBSapwood,LCSapwood,LOSapwood,HASapwood,HBSapwood,HCSapwood,HOSapwood)
PlotLevel$Density<-substr(PlotLevel$ID, 0,1)
PlotLevel$Geno<-substr(PlotLevel$ID,2,2)

#write_xlsx(PlotLevel, "../Data/Processed/Sapwood/PlotLevelSapwood.xlsx")

```


```{r}
PlotLevelSapwoodArea<-ggplot(PlotLevel, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Area, color=ID))+
  ggtitle("Plot Level Sapwood Area")
PlotLevelSapwoodArea

ggsave("../Data/Processed/Sapwood/PlotLevelSapwoodArea.jpg", PlotLevelSapwoodArea, height = 7, width = 10, units = "in", dpi = 500)
```


```{r}
summary(LA1$Sapwood)
summary(LB1$Sapwood)
summary(LC1$Sapwood)
summary(LO1$Sapwood)
summary(HA1$Sapwood)
summary(HB1$Sapwood)
summary(HC1$Sapwood)
summary(HO1$Sapwood)

summary(LA2$Sapwood)
summary(LB2$Sapwood)
summary(LC2$Sapwood)
summary(LO2$Sapwood)
summary(HA2$Sapwood)
summary(HB2$Sapwood)
summary(HC2$Sapwood)
summary(HO2$Sapwood)

summary(LA3$Sapwood)
summary(LB3$Sapwood)
summary(LC3$Sapwood)
summary(LO3$Sapwood)
summary(HA3$Sapwood)
summary(HB3$Sapwood)
summary(HC3$Sapwood)
summary(HO3$Sapwood)

summary(LA4$Sapwood)
summary(LB4$Sapwood)
summary(LC4$Sapwood)
summary(LO4$Sapwood)
summary(HA4$Sapwood)
summary(HB4$Sapwood)
summary(HC4$Sapwood)
summary(HO4$Sapwood)

#install.packages("plotrix")
library(plotrix)
std.error(LA1$Sapwood)
std.error(LB1$Sapwood)
std.error(LC1$Sapwood)
std.error(LO1$Sapwood)
std.error(HA1$Sapwood)
std.error(HB1$Sapwood)
std.error(HC1$Sapwood)
std.error(HO1$Sapwood)

std.error(LA2$Sapwood)
std.error(LB2$Sapwood)
std.error(LC2$Sapwood)
std.error(LO2$Sapwood)
std.error(HA2$Sapwood)
std.error(HB2$Sapwood)
std.error(HC2$Sapwood)
std.error(HO2$Sapwood)

std.error(LA3$Sapwood)
std.error(LB3$Sapwood)
std.error(LC3$Sapwood)
std.error(LO3$Sapwood)
std.error(HA3$Sapwood)
std.error(HB3$Sapwood)
std.error(HC3$Sapwood)
std.error(HO3$Sapwood)

std.error(LA4$Sapwood)
std.error(LB4$Sapwood)
std.error(LC4$Sapwood)
std.error(LO4$Sapwood)
std.error(HA4$Sapwood)
std.error(HB4$Sapwood)
std.error(HC4$Sapwood)
std.error(HO4$Sapwood)

```