---
title: "PlotSapflow"
author: "Azura Liu"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("tidyverse")
library("lubridate")
library("readxl")
library("writexl")

getwd()
Sections<-read_excel("../Data/Processed/Sapwood/17SectionalSums.xlsx")
Sapflux<-read_excel("../Data/Processed/Daytime/sapflow/Sapflux.5.xlsx")
```

```{r}
LA<-Sapflux%>%
  mutate(ID = "LA")%>%
  filter(grepl("LA",Tree))%>%
  select(36, 4:35)

LAFlux<-aggregate(LA[3:33], by = list(LA$Position,LA$ID),FUN = "mean")

LB<-Sapflux%>%
  mutate(ID = "LB")%>%
  filter(grepl("LB",Tree))%>%
  select(36, 4:35)

LBFlux<-aggregate(LB[3:33], by = list(LB$Position,LB$ID),FUN = "mean")

LC<-Sapflux%>%
  mutate(ID = "LC")%>%
  filter(grepl("LC",Tree))%>%
  select(36, 4:35)

LCFlux<-aggregate(LC[3:33], by = list(LC$Position,LC$ID),FUN = "mean")

LO<-Sapflux%>%
  mutate(ID = "LO")%>%
  filter(grepl("LO",Tree))%>%
  select(36, 4:35)

LOFlux<-aggregate(LO[3:33], by = list(LO$Position,LO$ID),FUN = "mean")

#HA<-Sapflux%>%
 # mutate(ID = "HA")%>%
  #filter(grepl("HA",Tree))%>%
  #select(36, 4:35)

#HAFlux<-aggregate(HA[3:33], by = list(HA$Position,HA$ID),FUN = "mean")

#HB<-Sapflux%>%
 # mutate(ID = "HB")%>%
#  filter(grepl("HB",Tree))%>%
#  select(36, 4:35)

#HBFlux<-aggregate(HB[3:33], by = list(HB$Position,HB$ID),FUN = "mean")

HC<-Sapflux%>%
  mutate(ID = "HC")%>%
  filter(grepl("HC",Tree))%>%
  select(36, 4:35)

HCFlux<-aggregate(HC[3:33], by = list(HC$Position,HC$ID),FUN = "mean")

HO<-Sapflux%>%
  mutate(ID = "HO")%>%
  filter(grepl("HO",Tree))%>%
  select(36, 4:35)

HOFlux<-aggregate(HO[3:33], by = list(HO$Position,HO$ID),FUN = "mean")


SapfluxbyPop<-rbind(LAFlux,LBFlux,LCFlux,LOFlux,HCFlux,HOFlux)

names(SapfluxbyPop)[1]<-"Section"
names(SapfluxbyPop)[2]<-"ID"

```

```{r}
names(Sections)[4]<-"LA"
names(Sections)[5]<-"LB"
names(Sections)[6]<-"LC"
names(Sections)[7]<-"LO"
names(Sections)[8]<-"HA"
names(Sections)[9]<-"HB"
names(Sections)[10]<-"HC"
names(Sections)[11]<-"HO"


SectionWrangle<-Sections%>%
  pivot_longer(cols = LA:HO, names_to = "ID", values_to = "Area")

SapfluxbyPop$Section <- gsub("I","Inner",SapfluxbyPop$Section)
SapfluxbyPop$Section <- gsub("O","Outer",SapfluxbyPop$Section)

SapfluxWrangle<-SapfluxbyPop%>%
  pivot_longer(cols = 3:33, names_to = "DOY", values_to = "Sapflux")

Deep<-SapfluxWrangle%>%
  filter(Section == "Inner")%>%
  mutate(Sapflux=Sapflux/2)
Deep$Section<-gsub("Inner","Deep",Deep$Section)

SapfluxJuly<-rbind(SapfluxWrangle,Deep)
```

```{r}
SectionJuly<-SectionWrangle%>%
  subset(DOY>120 & DOY <152)
SapfluxJuly$DOY<-as.double(SapfluxJuly$DOY)

JulySapflow<-inner_join(SectionJuly, SapfluxJuly,by = c("DOY", "Section", "ID"))%>%
  mutate(Sapflow=Sapflux*Area/10000)

Weather<-read.csv("../Data/Processed/Daytime/Sapflux/converted/Sap1.5.csv")
Weather$DOY<-as.numeric(Weather$DOY)
Weather$VPD<-as.numeric(Weather$VPD)

VPD<-aggregate(Weather$VPD, by=list(Weather$DOY), mean)
  names(VPD)[1]<-"DOY"
  names(VPD)[2]<-"VPD"


JulyMeta<-inner_join(JulySapflow, VPD, by="DOY")

#write_xlsx(JulyMeta, "../Data/Processed/Sapflow/Jul17/PlotLevelSapflow.xlsx")
```

```{r}

LAFlow1<-JulyMeta%>%
  filter(ID == "LA" & Block == 1)
LAFlow2<-JulyMeta%>%
  filter(ID == "LA" & Block == 2)
LAFlow3<-JulyMeta%>%
  filter(ID == "LA" & Block == 3)
LAFlow4<-JulyMeta%>%
  filter(ID == "LA" & Block == 4)


LBFlow1<-JulyMeta%>%
  filter(ID == "LB" & Block == 1)
LBFlow2<-JulyMeta%>%
  filter(ID == "LB" & Block == 2)
LBFlow3<-JulyMeta%>%
  filter(ID == "LB" & Block == 3)
LBFlow4<-JulyMeta%>%
  filter(ID == "LB" & Block == 4)


LCFlow1<-JulyMeta%>%
  filter(ID == "LC" & Block == 1)
LCFlow2<-JulyMeta%>%
  filter(ID == "LC" & Block == 2)
LCFlow3<-JulyMeta%>%
  filter(ID == "LC" & Block == 3)
LCFlow4<-JulyMeta%>%
  filter(ID == "LC" & Block == 4)


LOFlow1<-JulyMeta%>%
  filter(ID == "LO" & Block == 1)
LOFlow2<-JulyMeta%>%
  filter(ID == "LO" & Block == 2)
LOFlow3<-JulyMeta%>%
  filter(ID == "LO" & Block == 3)
LOFlow4<-JulyMeta%>%
  filter(ID == "LO" & Block == 4)


HAFlow1<-JulyMeta%>%
  filter(ID == "HA" & Block == 1)
HAFlow2<-JulyMeta%>%
  filter(ID == "HA" & Block == 2)
HAFlow3<-JulyMeta%>%
  filter(ID == "HA" & Block == 3)
HAFlow4<-JulyMeta%>%
  filter(ID == "HA" & Block == 4)


HBFlow1<-JulyMeta%>%
  filter(ID == "HB" & Block == 1)
HBFlow2<-JulyMeta%>%
  filter(ID == "HB" & Block == 2)
HBFlow3<-JulyMeta%>%
  filter(ID == "HB" & Block == 3)
HBFlow4<-JulyMeta%>%
  filter(ID == "HB" & Block == 4)


HCFlow1<-JulyMeta%>%
  filter(ID == "HC" & Block == 1)
HCFlow2<-JulyMeta%>%
  filter(ID == "HC" & Block == 2)
HCFlow3<-JulyMeta%>%
  filter(ID == "HC" & Block == 3)
HCFlow4<-JulyMeta%>%
  filter(ID == "HC" & Block == 4)


HOFlow1<-JulyMeta%>%
  filter(ID == "HO" & Block == 1)
HOFlow2<-JulyMeta%>%
  filter(ID == "HO" & Block == 2)
HOFlow3<-JulyMeta%>%
  filter(ID == "HO" & Block == 3)
HOFlow4<-JulyMeta%>%
  filter(ID == "HO" & Block == 4)
```

```{r eval=FALSE, include=FALSE}
LASapflow1<-ggplot(LAFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LA1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA1.jpg", LASapflow1, height = 7, width = 10, units = "in", dpi = 500)

LASapflow2<-ggplot(LAFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LA2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA2.jpg", LASapflow2, height = 7, width = 10, units = "in", dpi = 500)

LASapflow3<-ggplot(LAFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LA3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA3.jpg", LASapflow3, height = 7, width = 10, units = "in", dpi = 500)

LASapflow4<-ggplot(LAFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LA4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA4.jpg", LASapflow4, height = 7, width = 10, units = "in", dpi = 500)


LBSapflow1<-ggplot(LBFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LB1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB1.jpg", LBSapflow1, height = 7, width = 10, units = "in", dpi = 500)

LBSapflow2<-ggplot(LBFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LB2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB2.jpg", LBSapflow2, height = 7, width = 10, units = "in", dpi = 500)

LBSapflow3<-ggplot(LBFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LB3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB3.jpg", LBSapflow3, height = 7, width = 10, units = "in", dpi = 500)

LBSapflow4<-ggplot(LBFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LB4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB4.jpg", LBSapflow4, height = 7, width = 10, units = "in", dpi = 500)

LCSapflow1<-ggplot(LCFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LC1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC1.jpg", LCSapflow1, height = 7, width = 10, units = "in", dpi = 500)

LCSapflow2<-ggplot(LCFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LC2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC2.jpg", LCSapflow2, height = 7, width = 10, units = "in", dpi = 500)

LCSapflow3<-ggplot(LCFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LC3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC3.jpg", LCSapflow3, height = 7, width = 10, units = "in", dpi = 500)

LCSapflow4<-ggplot(LCFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LC4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC4.jpg", LCSapflow4, height = 7, width = 10, units = "in", dpi = 500)

LOSapflow1<-ggplot(LOFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LO1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO1.jpg", LOSapflow1, height = 7, width = 10, units = "in", dpi = 500)

LOSapflow2<-ggplot(LOFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LO2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO2.jpg", LOSapflow2, height = 7, width = 10, units = "in", dpi = 500)

LOSapflow3<-ggplot(LOFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LO3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO3.jpg", LOSapflow3, height = 7, width = 10, units = "in", dpi = 500)

LOSapflow4<-ggplot(LOFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("LO4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO4.jpg", LOSapflow4, height = 7, width = 10, units = "in", dpi = 500)

HASapflow1<-ggplot(HAFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HA1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA1.jpg", HASapflow1, height = 7, width = 10, units = "in", dpi = 500)

HASapflow2<-ggplot(HAFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HA2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA2.jpg", HASapflow2, height = 7, width = 10, units = "in", dpi = 500)

HASapflow3<-ggplot(HAFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HA3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA3.jpg", HASapflow3, height = 7, width = 10, units = "in", dpi = 500)

HASapflow4<-ggplot(HAFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HA4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA4.jpg", HASapflow4, height = 7, width = 10, units = "in", dpi = 500)

HBSapflow1<-ggplot(HBFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HB1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB1.jpg", HBSapflow1, height = 7, width = 10, units = "in", dpi = 500)

HBSapflow2<-ggplot(HBFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HB2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB2.jpg", HBSapflow2, height = 7, width = 10, units = "in", dpi = 500)

HBSapflow3<-ggplot(HBFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HB3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB3.jpg", HBSapflow3, height = 7, width = 10, units = "in", dpi = 500)

HBSapflow4<-ggplot(HBFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HB4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB4.jpg", HBSapflow4, height = 7, width = 10, units = "in", dpi = 500)

HCSapflow1<-ggplot(HCFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HC1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC1.jpg", HCSapflow1, height = 7, width = 10, units = "in", dpi = 500)

HCSapflow2<-ggplot(HCFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HC2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC2.jpg", HCSapflow2, height = 7, width = 10, units = "in", dpi = 500)

HCSapflow3<-ggplot(HCFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HC3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC3.jpg", HCSapflow3, height = 7, width = 10, units = "in", dpi = 500)

HCSapflow4<-ggplot(HCFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HC4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC4.jpg", HCSapflow4, height = 7, width = 10, units = "in", dpi = 500)

HOSapflow1<-ggplot(HOFlow1, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HO1 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO1.jpg", HOSapflow1, height = 7, width = 10, units = "in", dpi = 500)

HOSapflow2<-ggplot(HOFlow2, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HO2 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO2.jpg", HOSapflow2, height = 7, width = 10, units = "in", dpi = 500)

HOSapflow3<-ggplot(HOFlow3, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HO3 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO3.jpg", HOSapflow3, height = 7, width = 10, units = "in", dpi = 500)

HOSapflow4<-ggplot(HOFlow4, aes(DOY))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color=Section))+
  geom_point(aes(y=VPD, color = "VPD"))+
  ggtitle("HO4 Plot Level Sapflow")

ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO4.jpg", HOSapflow4, height = 7, width = 10, units = "in", dpi = 500)
```

```{r}

PlotLevel<-aggregate(JulyMeta$Sapflow, by = list(JulyMeta$DOY, JulyMeta$Block, JulyMeta$ID),FUN = "sum")
names(PlotLevel)[1]<-"DOY"
names(PlotLevel)[2]<-"Block"
names(PlotLevel)[3]<-"ID"
names(PlotLevel)[4]<-"Sapflow"

PlotLevel<-inner_join(PlotLevel, VPD, by="DOY")

write_xlsx(PlotLevel, "../Data/Processed/Daytime/sapflow/Sapflow.5.xlsx")
```

```{r}
Mean<-aggregate(PlotLevel[4:5],by=list(PlotLevel$DOY,PlotLevel$ID), FUN = "mean")
names(Mean)[1]<-"DOY"
names(Mean)[2]<-"ID"

GA<-filter(Mean,ID == "LA" | ID =="HA")
GB<-filter(Mean,ID == "LB" | ID =="HB")
GC<-filter(Mean,ID == "LC" | ID =="HC")
GO<-filter(Mean,ID == "LO" | ID =="HO")

A<-ggplot(GA, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color= ID))+
  ggtitle("Genotype A High vs Low Density")

A
ggsave("../Data/Processed/Daytime/sapflow/plots/5A.jpg", A, height = 7, width = 10, units = "in", dpi = 500)

B<-ggplot(GB, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color= ID))+
  ggtitle("Genotype B High vs Low Density")

B
ggsave("../Data/Processed/Daytime/sapflow/plots/5B.jpg", B, height = 7, width = 10, units = "in", dpi = 500)

C<-ggplot(GC, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color= ID))+
  ggtitle("Genotype C High vs Low Density")

C
ggsave("../Data/Processed/Daytime/sapflow/plots/5C.jpg", C, height = 7, width = 10, units = "in", dpi = 500)

O<-ggplot(GO, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow, color= ID))+
  ggtitle("Genotype O High vs Low Density")

O
ggsave("../Data/Processed/Daytime/sapflow/plots/5O.jpg", O, height = 7, width = 10, units = "in", dpi = 500)
```

```{r eval=FALSE, include=FALSE}
HA1<-PlotLevel%>%filter(Block==1 & ID == "HA")

HAB1<-ggplot(HA1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HA1 Plot Level Sapflow vs VPD")

HAB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA1.jpg", HAB1, height = 7, width = 10, units = "in", dpi = 500)

HB1<-PlotLevel%>%filter(Block==1 & ID == "HB")

HBB1<-ggplot(HB1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HB1 Plot Level Sapflow vs VPD")

HBB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB1.jpg", HBB1, height = 7, width = 10, units = "in", dpi = 500)

HC1<-PlotLevel%>%filter(Block==1 & ID == "HC")
HCB1<-ggplot(HC1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HC1 Plot Level Sapflow vs VPD")

HCB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC1.jpg", HCB1, height = 7, width = 10, units = "in", dpi = 500)

HO1<-PlotLevel%>%filter(Block==1 & ID == "HO")

HOB1<-ggplot(HO1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HO1 Plot Level Sapflow vs VPD")

HOB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO1.jpg", HOB1, height = 7, width = 10, units = "in", dpi = 500)

#HAHBHCHO
```

```{r}
HA2<-PlotLevel%>%filter(Block==2 & ID == "HA")

HAB2<-ggplot(HA2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HA2 Plot Level Sapflow vs VPD")

HAB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA2.jpg", HAB2, height = 7, width = 10, units = "in", dpi = 500)

HB2<-PlotLevel%>%filter(Block==2 & ID == "HB")

HBB2<-ggplot(HB2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HB2 Plot Level Sapflow vs VPD")

HBB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB2.jpg", HBB2, height = 7, width = 10, units = "in", dpi = 500)

HC2<-PlotLevel%>%filter(Block==2 & ID == "HC")
HCB2<-ggplot(HC2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HC2 Plot Level Sapflow vs VPD")

HCB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC2.jpg", HCB2, height = 7, width = 10, units = "in", dpi = 500)

HO2<-PlotLevel%>%filter(Block==2 & ID == "HO")

HOB2<-ggplot(HO2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HO2 Plot Level Sapflow vs VPD")

HOB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO2.jpg", HOB2, height = 7, width = 10, units = "in", dpi = 500)

#HAHBHCHO
```
```{r}
HA3<-PlotLevel%>%filter(Block==3 & ID == "HA")

HAB3<-ggplot(HA3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HA3 Plot Level Sapflow vs VPD")

HAB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA3.jpg", HAB3, height = 7, width = 10, units = "in", dpi = 500)

HB3<-PlotLevel%>%filter(Block==3 & ID == "HB")

HBB3<-ggplot(HB3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HB3 Plot Level Sapflow vs VPD")

HBB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB3.jpg", HBB3, height = 7, width = 10, units = "in", dpi = 500)

HC3<-PlotLevel%>%filter(Block==3 & ID == "HC")
HCB3<-ggplot(HC3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HC3 Plot Level Sapflow vs VPD")

HCB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC3.jpg", HCB3, height = 7, width = 10, units = "in", dpi = 500)

HO3<-PlotLevel%>%filter(Block==3 & ID == "HO")

HOB3<-ggplot(HO3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HO3 Plot Level Sapflow vs VPD")

HOB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO3.jpg", HOB3, height = 7, width = 10, units = "in", dpi = 500)

#HAHBHCHO
```
```{r}
HA4<-PlotLevel%>%filter(Block==4 & ID == "HA")

HAB4<-ggplot(HA4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HA4 Plot Level Sapflow vs VPD")

HAB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HA4.jpg", HAB4, height = 7, width = 10, units = "in", dpi = 500)

HB4<-PlotLevel%>%filter(Block==4 & ID == "HB")

HBB4<-ggplot(HB4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HB4 Plot Level Sapflow vs VPD")

HBB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HB4.jpg", HBB4, height = 7, width = 10, units = "in", dpi = 500)

HC4<-PlotLevel%>%filter(Block==4 & ID == "HC")
HCB4<-ggplot(HC4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HC4 Plot Level Sapflow vs VPD")

HCB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HC4.jpg", HCB4, height = 7, width = 10, units = "in", dpi = 500)

HO4<-PlotLevel%>%filter(Block==4 & ID == "HO")

HOB4<-ggplot(HO4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("HO4 Plot Level Sapflow vs VPD")

HOB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/HO4.jpg", HOB4, height = 7, width = 10, units = "in", dpi = 500)

#HAHBHCHO
```


```{r}
LA1<-PlotLevel%>%filter(Block==1 & ID == "LA")

LAB1<-ggplot(LA1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LA1 Plot Level Sapflow vs VPD")

LAB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA1.jpg", LAB1, height = 7, width = 10, units = "in", dpi = 500)

LB1<-PlotLevel%>%filter(Block==1 & ID == "LB")

LBB1<-ggplot(LB1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LB1 Plot Level Sapflow vs VPD")

LBB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB1.jpg", LBB1, height = 7, width = 10, units = "in", dpi = 500)

LC1<-PlotLevel%>%filter(Block==1 & ID == "LC")
LCB1<-ggplot(LC1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LC1 Plot Level Sapflow vs VPD")

LCB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC1.jpg", LCB1, height = 7, width = 10, units = "in", dpi = 500)

LO1<-PlotLevel%>%filter(Block==1 & ID == "LO")

LOB1<-ggplot(LO1, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LO1 Plot Level Sapflow vs VPD")

LOB1
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO1.jpg", LOB1, height = 7, width = 10, units = "in", dpi = 500)

#LALBLCLO
```

```{r}
LA2<-PlotLevel%>%filter(Block==2 & ID == "LA")

LAB2<-ggplot(LA2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LA2 Plot Level Sapflow vs VPD")

LAB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA2.jpg", LAB2, height = 7, width = 10, units = "in", dpi = 500)

LB2<-PlotLevel%>%filter(Block==2 & ID == "LB")

LBB2<-ggplot(LB2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LB2 Plot Level Sapflow vs VPD")

LBB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB2.jpg", LBB2, height = 7, width = 10, units = "in", dpi = 500)

LC2<-PlotLevel%>%filter(Block==2 & ID == "LC")
LCB2<-ggplot(LC2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LC2 Plot Level Sapflow vs VPD")

LCB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC2.jpg", LCB2, height = 7, width = 10, units = "in", dpi = 500)

LO2<-PlotLevel%>%filter(Block==2 & ID == "LO")

LOB2<-ggplot(LO2, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LO2 Plot Level Sapflow vs VPD")

LOB2
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO2.jpg", LOB2, height = 7, width = 10, units = "in", dpi = 500)

#LALBLCLO
```
```{r}
LA3<-PlotLevel%>%filter(Block==3 & ID == "LA")

LAB3<-ggplot(LA3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LA3 Plot Level Sapflow vs VPD")

LAB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA3.jpg", LAB3, height = 7, width = 10, units = "in", dpi = 500)

LB3<-PlotLevel%>%filter(Block==3 & ID == "LB")

LBB3<-ggplot(LB3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LB3 Plot Level Sapflow vs VPD")

LBB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB3.jpg", LBB3, height = 7, width = 10, units = "in", dpi = 500)

LC3<-PlotLevel%>%filter(Block==3 & ID == "LC")
LCB3<-ggplot(LC3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LC3 Plot Level Sapflow vs VPD")

LCB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC3.jpg", LCB3, height = 7, width = 10, units = "in", dpi = 500)

LO3<-PlotLevel%>%filter(Block==3 & ID == "LO")

LOB3<-ggplot(LO3, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LO3 Plot Level Sapflow vs VPD")

LOB3
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO3.jpg", LOB3, height = 7, width = 10, units = "in", dpi = 500)

#LALBLCLO
```
```{r}
LA4<-PlotLevel%>%filter(Block==4 & ID == "LA")

LAB4<-ggplot(LA4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LA4 Plot Level Sapflow vs VPD")

LAB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LA4.jpg", LAB4, height = 7, width = 10, units = "in", dpi = 500)

LB4<-PlotLevel%>%filter(Block==4 & ID == "LB")

LBB4<-ggplot(LB4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LB4 Plot Level Sapflow vs VPD")

LBB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LB4.jpg", LBB4, height = 7, width = 10, units = "in", dpi = 500)

LC4<-PlotLevel%>%filter(Block==4 & ID == "LC")
LCB4<-ggplot(LC4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LC4 Plot Level Sapflow vs VPD")

LCB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LC4.jpg", LCB4, height = 7, width = 10, units = "in", dpi = 500)

LO4<-PlotLevel%>%filter(Block==4 & ID == "LO")

LOB4<-ggplot(LO4, aes(VPD))+
  scale_x_continuous()+
  geom_point(aes(y=Sapflow))+
  ggtitle("LO4 Plot Level Sapflow vs VPD")

LOB4
ggsave("../Data/Processed/Sapflow/Jul17/SapflowGraphs/LO4.jpg", LOB4, height = 7, width = 10, units = "in", dpi = 500)

#LALBLCLO
```