---
title: "WholeAOV"
author: "Azura Liu"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstatix)
library("dplyr")
library("tidyverse")
library("lubridate")
library("readxl")
library(writexl)
library(datarium)
library(lme4)
library(lmerTest)
library(emmeans)
library(drc)
library(nlme)
library(nlstools)
library(multcomp)

getwd()
Sapflow<-read_xlsx("../Data/Processed/Daytime/sapflow/Join_4Blocks.xlsx")

```

```{r}
m0<-aov(SapflowPerGroundArea~REW+ID+(1|Block), data = Sapflow)

Anova(m0,type="II")

postHocs <- glht(m0, linfct = mcp(technique = "Tukey"))
summary(postHocs)


summary(m0)
aov(m0)

m0a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Sapflow)
emmeans(m0a, ~Density:Geno,data=Sapflow)

```

```{r}

Sapflow$Week <- cut(Sapflow$DOY,
              breaks=c(0, 156,161,166,171,176,181,186,191,196,201,206,211,216,221,226,231,236,241,246,251,256,261,266,271,276),
              labels=c('1', '2', '3', '4',"5","6","7","8","9","10","11","12","13","14","15","16", "17","18","19","20", "21","22", "23","24","25" ))
Sapflow$SapwoodPerGroundArea<-Sapflow$SapwoodArea/Sapflow$GroundArea

m0<-aov(SapflowPerGroundArea~VPD+Density*Geno*DOY+(1|Block), data = Sapflow,type="II")
summary(m0)

emmeans(m0, ~Density:Geno,data=Sapflow)

pwc <- Sapflow %>% 
  emmeans_test(
    SapflowPerGroundArea ~ Geno, covariate = VPD,
    p.adjust.method = "bonferroni"
    )
pwc

write.table(pwc , file = "../Data/Processed/Daytime/sapflow/pwc.csv")

res.aov <- Sapflow %>% 
  anova_test(SapflowPerGroundArea ~ VPD+REW + Density*Geno*DOY+(1|Block))
get_anova_table(res.aov)




```

```{r}
Full<-aggregate(cbind(REW, VPD,SapwoodPerGroundArea,SapflowPerGroundArea)~Week+Density+Geno, data=Sapflow, mean)
#write_xlsx(Full, "../Data/Processed/Daytime/sapflow/WeeklyAverages.xlsx")

Full<-read_xlsx( "../Data/Processed/Daytime/sapflow/WeeklyAverages.xlsx")%>%
  mutate(ID=paste0(Density,Geno))


HA<-Full%>%filter(ID=="HA")
LA<-Full%>%filter(ID=="LA")
HB<-Full%>%filter(ID=="HB")
LB<-Full%>%filter(ID=="LB")
HC<-Full%>%filter(ID=="HC")
LC<-Full%>%filter(ID=="LC")
HO<-Full%>%filter(ID=="HO")
LO<-Full%>%filter(ID=="LO")

REWLM<-ggplot(Full,aes(x=REW,y=SapflowPerGroundArea,color=ID))+
  geom_point()+
  geom_smooth(method=lm,se = FALSE)
REWLM   

plot(HA$REW,HA$SapflowPerGroundArea)
print(NLSstAsymptotic(sortedXyData(expression(VPD),
                                    expression(SapflowPerGroundArea),
                                    HO)),digits=3)



with(Full, plot(VPD, SapflowPerGroundArea, xlim=c(0, 30), ylim=c(0,75)))
curve(fx(x, Asym=p["Asym"], R0=p["R0"], lrc=p["lrc"]), 
      add=T, col="red")

a<-ggplot(Full,aes(x=log(REW),y=(SapflowPerGroundArea),color=ID))+
  geom_point(size=4,alpha=0.9)+
  geom_smooth(method=lm,se = FALSE, alpha=0.5)+
  ylab("Sapflow per Ground Area (kg/m^2)")
a
ggsave("../Data/Processed/Daytime/sapflow/plots/REWSapflowbyGroup.jpg", a, height = 7, width = 10, units = "in", dpi = 500)


```

```{r}
Environ<-ggplot(REW,aes(x=DOY))+
  geom_point(aes(y=REW, color = Density,size = 1))+
  geom_point(aes(y=VPD, color = "VPD", size = 1))+
  scale_y_continuous(
    name = "REW",
    sec.axis = sec_axis(~.,name = "VPD")
  )+ theme(axis.text = element_text(size = 20))+
  theme(axis.title.y = element_text(size = 20))+ 
  theme(axis.title.x = element_text(size = 20))+
  theme(legend.text = element_text(size = 20))+ 
  theme(legend.title = element_text(size = 20)) +
  guides(shape = guide_legend(override.aes = list(size = 40)))
Environ
ggsave("../Data/Processed/Daytime/sapflow/plots/ENV/REWnVPD.jpg",  Environ, height = 10, width = 20, units = "in", dpi = 200)

ggsave("../Data/Processed/Daytime/sapflow/plots/WeeklyAverages/REWbyGroup.jpg", REW, height = 10, width = 10, units = "in", dpi = 500)

```

```{r}
Week<-Sapflow%>%
  filter(Week == 1)
m1<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m1
summary(aov(m1))
summary(m1)



m1a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m1a, ~Density:Geno,data=Week)
```


```{r}
Week<-Sapflow%>%
  filter(Week == 2)
m2<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m2
summary(aov(m2))
summary(m2)



m2a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m2a, ~Density:Geno,data=Week)
```
```{r}
Week<-Sapflow%>%
  filter(Week == 3)
m3<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m3
summary(aov(m3))
summary(m3)



m3a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m3a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 4)
m4<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m4
summary(aov(m4))
summary(m4)



m4a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m4a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 5)
m5<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m5
summary(aov(m5))
summary(m5)



m5a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m5a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 6)
m6<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m6
summary(aov(m6))
summary(m6)



m6a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m6a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 7)
m7<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m7
summary(aov(m7))
summary(m7)



m7a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m7a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 8)
m8<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m8
summary(aov(m8))
summary(m8)



m8a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m8a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 9)
m9<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m9
summary(aov(m9))
summary(m9)



m9a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m9a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 10)
m10<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m10
summary(aov(m10))
summary(m10)



m10a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m10a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 11)
m11<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m11
summary(aov(m11))
summary(m11)



m11a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m11a, ~Density:Geno,data=Week)
```


```{r}
Week<-Sapflow%>%
  filter(Week == 12)
m12<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m12
summary(aov(m12))
summary(m12)



m12a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m12a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 13)
m13<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m13
summary(aov(m13))
summary(m13)



m13a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m13a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 14)
m14<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m14
summary(aov(m14))
summary(m14)



m14a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m14a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 15)
m15<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m15
summary(aov(m15))
summary(m15)



m15a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m15a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 16)
m16<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m16
summary(aov(m16))
summary(m16)



m16a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m16a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 17)
m17<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m17
summary(aov(m17))
summary(m17)



m17a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m17a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 18)
m18<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m18
summary(aov(m18))
summary(m18)



m18a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m18a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 19)
m19<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m19
summary(aov(m19))
summary(m19)



m19a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m19a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 20)
m20<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m20
summary(aov(m20))
summary(m20)



m20a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m20a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 21)
m21<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m21
summary(aov(m21))
summary(m21)



m21a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m21a, ~Density:Geno,data=Week)
```


```{r}
Week<-Sapflow%>%
  filter(Week == 22)
m22<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m22
summary(aov(m22))
summary(m22)



m22a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m22a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 23)
m23<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m23
summary(aov(m23))
summary(m23)



m23a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m23a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 24)
m24<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m24
summary(aov(m24))
summary(m24)



m24a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m24a, ~Density:Geno,data=Week)
```

```{r}
Week<-Sapflow%>%
  filter(Week == 25)
m25<-lm(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)

m25
summary(aov(m25))
summary(m25)



m25a<-aov(SapflowPerGroundArea~Density*Geno*DOY+(1|Block), data = Week)
emmeans(m25a, ~Density:Geno,data=Week)
```
